/**
 * @file   ProbeApp.cpp
 * @brief  Implementation of ProbeApp component.
 * @details Portable C++ implementation generated by
 *          the Code Generation Pipeline.
 *          Uses runtime::IRuntime for all platform-dependent behavior.
 * @author  Engineering Team
 * @version 1.0.0
 * @copyright Copyright (c) 2024 Company. All rights reserved.
 */

#include "ProbeApp/ProbeApp.hpp"

#include "CanConsumer/CanConsumer.hpp"
#include "ProbeCommVariant/ProbeCommVariant.hpp"

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <deque>
#include <iostream>
#include <mutex>
#include <stdexcept>
#include <thread>
#include <vector>

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

// =============================================================================
// Internal constants — not exposed in the header
// =============================================================================

/**
 * @brief   Maximum number of entries in the 100 ms CAN ring buffer.
 * @details Sized to hold 10 seconds of 100 ms samples (100 entries) providing
 *          the full pre-trigger retention window at the 100 ms sampling rate.
 *          Range: fixed at 100 entries.
 */
static constexpr uint32_t kMaxBuffer100ms{100U};

/**
 * @brief   Maximum number of entries in the 1000 ms CAN ring buffer.
 * @details Sized to hold 10 seconds of 1000 ms samples (10 entries) providing
 *          the full pre-trigger retention window at the 1000 ms sampling rate.
 *          Range: fixed at 10 entries.
 */
static constexpr uint32_t kMaxBuffer1000ms{10U};

/**
 * @brief   Default past data retention count for the log data set rolling buffer.
 * @details Configures the rolling log buffer to retain 10 per-second log data sets,
 *          corresponding to a 10-second pre-trigger history window per SWR-REQ-03-01-009.
 */
static constexpr uint32_t kDefaultPastDataRetentionCount{10U};

/**
 * @brief   Capacity reservation for the 100 ms steady-state staging buffer.
 * @details Pre-allocated to avoid runtime heap growth during cyclic execution.
 *          Sized for a single serialised 100 ms CAN frame (256 bytes typical).
 */
static constexpr std::size_t kSteadyState100msReserve{256U};

/**
 * @brief   Capacity reservation for the 1000 ms steady-state staging buffer.
 * @details Pre-allocated to avoid runtime heap growth during cyclic execution.
 *          Sized for a single serialised 1000 ms CAN frame (512 bytes typical).
 */
static constexpr std::size_t kSteadyState1000msReserve{512U};

/**
 * @brief   Capacity reservation for the event sending buffer.
 * @details Pre-allocated to avoid runtime heap growth during event processing.
 *          Sized for a typical event payload (1024 bytes).
 */
static constexpr std::size_t kEventSendingBufferReserve{1024U};

/**
 * @brief   Capacity reservation for the image data buffer.
 * @details Pre-allocated to avoid runtime heap growth during image acquisition.
 *          Sized for a compressed camera frame (65536 bytes typical).
 */
static constexpr std::size_t kImageDataBufferReserve{65536U};

// =============================================================================
// Internal helper: obtain a monotonic timestamp in seconds (uint32_t)
// =============================================================================

/**
 * @brief   Returns the current monotonic clock value in seconds.
 * @details Uses std::chrono::steady_clock to obtain a monotonic, non-adjustable
 *          timestamp. The value is cast to uint32_t; wrap-around after ~136 years
 *          is acceptable for startup-delay enforcement purposes.
 * @return  Current monotonic time in whole seconds as uint32_t.
 * @throws  None — noexcept.
 */
static uint32_t GetTimestampSeconds() noexcept
{
    const auto now{std::chrono::steady_clock::now().time_since_epoch()};
    const uint64_t seconds{static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::seconds>(now).count())};
    return static_cast<uint32_t>(seconds & 0xFFFFFFFFU);
}

/**
 * @brief   Returns the current monotonic clock value in milliseconds.
 * @details Uses std::chrono::steady_clock to obtain a monotonic timestamp in
 *          milliseconds. Used for cycle-boundary enforcement in Run().
 * @return  Current monotonic time in whole milliseconds as uint64_t.
 * @throws  None — noexcept.
 */
static uint64_t GetTimestampMs() noexcept
{
    const auto now{std::chrono::steady_clock::now().time_since_epoch()};
    return static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::milliseconds>(now).count());
}

// =============================================================================
// ProbeApp Constructor
// =============================================================================

/**
 * @brief   Constructs ProbeApp with references to communication, variant, and CAN consumer.
 * @details Initialises all internal state, ring buffers, and variant-specific behaviour.
 *          Stores non-owning observer pointers to the provided collaborators; their
 *          lifetimes must exceed that of this ProbeApp instance.
 *          All member variables are initialised to safe default values.
 *          Validates critical dependency pointers and raises std::invalid_argument
 *          for null probeCommVariant or null canConsumer (fatal precondition violations).
 *          Applies variant configuration via the variant manager; falls back to the
 *          default variant code if ReadVariantCode fails.
 *          Performs capacity reservation on all buffer containers to eliminate
 *          runtime heap allocation during cyclic execution.
 * @param[in] comm     Non-owning pointer to the ProbeComm communication interface.
 *                     May be nullptr at construction; non-fatal — communication is
 *                     established in HandleInitialize(). Range: any pointer value.
 * @param[in] variant  Non-owning pointer to the ProbeCommVariant strategy object.
 *                     Must not be nullptr. Lifetime must exceed this object.
 * @param[in] canCons  Non-owning pointer to the CanConsumer shared-memory reader.
 *                     Must not be nullptr. Lifetime must exceed this object.
 * @pre     variant != nullptr && canCons != nullptr.
 * @post    All buffers are empty; isRunning_ == false; isDaqCommEstablished_ == false.
 * @throws  std::invalid_argument if variant or canCons is nullptr (FatalInitializationError).
 * @note    Called by: Main at startup.
 * @warning Passing nullptr for variant or canCons results in std::invalid_argument.
 *          Passing nullptr for comm is tolerated; communication is deferred to HandleInitialize.
 * @requirements SWR-REQ-01-01-002;SWR-REQ-01-01-003;SWR-REQ-01-02-001
 * @see     HandleInitialize
 */
ProbeApp::ProbeApp(ProbeComm* comm,
                   ProbeCommVariant* variant,
                   CanConsumer* canCons) noexcept
    : probeComm_{comm},
      probeCommVariant_{variant},
      canConsumer_{canCons},
      isRunning_{false},
      shutdownRequested_{false},
      isDaqCommEstablished_{false},
      collectionStarted_{false},
      msCounter_{0U},
      startupTimeSec_{0U},
      pastDataRetentionCount_{kDefaultPastDataRetentionCount}
{
    // Validate critical dependency: variant manager (fatal if null)
    if (probeCommVariant_ == nullptr) {
        // Fatal initialization error: variant manager required.
        // noexcept context: terminate is the defined behaviour for unrecoverable
        // precondition violations in safety-critical constructors.
        std::terminate();
    }

    // Validate critical dependency: CAN consumer (fatal if null)
    if (canConsumer_ == nullptr) {
        // Fatal initialization error: CAN data acquisition requires valid canConsumer.
        std::terminate();
    }

    // Initialize all boolean lifecycle flags to safe defaults
    isRunning_.store(false);
    isDaqCommEstablished_.store(false);
    shutdownRequested_.store(false);
    collectionStarted_ = false;

    // Initialize counters to zero
    msCounter_ = 0U;
    startupTimeSec_ = 0U;

    // Set configurable parameter: past data retention depth
    pastDataRetentionCount_ = kDefaultPastDataRetentionCount;

    // Initialize all buffer containers to empty state
    canBuffer100ms_null.clear();
    canBuffer1000ms_null.clear();
    logDataSetBuffer_null.clear();
    steadyStateDataBuffer100ms_null.clear();
    steadyStateDataBuffer1000ms_null.clear();
    eventSendingBuffer_null.clear();
    imageDataBuffer_null.clear();

    // Capacity reservation to eliminate runtime allocation during cyclic execution
    canBuffer100ms_null.reserve(static_cast<std::size_t>(kMaxBuffer100ms));
    canBuffer1000ms_null.reserve(static_cast<std::size_t>(kMaxBuffer1000ms));
    logDataSetBuffer_null.reserve(static_cast<std::size_t>(kDefaultPastDataRetentionCount));
    steadyStateDataBuffer100ms_null.reserve(kSteadyState100msReserve);
    steadyStateDataBuffer1000ms_null.reserve(kSteadyState1000msReserve);
    eventSendingBuffer_null.reserve(kEventSendingBufferReserve);
    imageDataBuffer_null.reserve(kImageDataBufferReserve);

    // Variant flags are applied inside ReadVariantCode() via SetVariant().
    probeCommVariant_->ReadVariantCode();

    // probeComm_ may be nullptr at this stage; non-fatal.
    // Communication establishment is deferred to HandleInitialize().
}

// =============================================================================
// ProbeApp Destructor
// =============================================================================

/**
 * @brief   Destroys the ProbeApp instance and releases all owned resources.
 * @details Ensures all RAII-managed resources (mutexes, buffers) are released
 *          cleanly. Does not perform network communication; HandleShutdown() or
 *          HandleTerminate() must be called before destruction for graceful teardown.
 * @pre     HandleTerminate() or HandleShutdown() has been called.
 * @post    All resources owned by this instance are released.
 * @throws  None.
 */
ProbeApp::~ProbeApp() noexcept = default;

// =============================================================================
// HandleInitialize
// =============================================================================

/**
 * @brief   Starts ProbeApp operation after ADAS ECU startup and initiates SOME/IP
 *          communication with DAQ.
 * @details Reads the variant code from shared memory and applies feature flags or
 *          falls back to the default variant code on failure. Sets isRunning_ to true,
 *          captures the startup reference timestamp, and initiates SOME/IP service
 *          discovery via ProbeComm. The isDaqCommEstablished_ flag is NOT set here;
 *          it is set only when the service discovery handshake completes, which is
 *          monitored within the cyclic Run() context.
 *          If InitiateSomeIpDiscovery fails, isDaqCommEstablished_ remains false and
 *          the Run() loop will retry discovery each cycle.
 * @pre     ProbeApp has been successfully constructed.
 * @post    isRunning_ == true; startupTimeSec_ captures the boot reference timestamp;
 *          SOME/IP service discovery is in progress.
 * @throws  None.
 * @note    Called by: Main after ECU boot sequence completes.
 * @warning Calling this method more than once results in undefined behaviour.
 * @requirements SWR-REQ-01-10-001;SWR-REQ-01-10-002;SWR-REQ-01-03-001;
 *               SWR-REQ-03-16-001;SWR-REQ-03-16-002
 * @see     Run, HandleTerminate
 */
void ProbeApp::HandleInitialize() noexcept
{
    // Step 1: Read variant code from shared memory (applies flags via SetVariant)
    probeCommVariant_->ReadVariantCode();

    // Step 2: Mark application as running
    isRunning_.store(true);

    // Step 3: Capture startup reference timestamp (seconds)
    startupTimeSec_ = GetTimestampSeconds();

    // Step 4: Initiate SOME/IP service discovery with DAQ
    // isDaqCommEstablished_ remains false until session confirmed in Run()
    if (probeComm_ != nullptr) {
        const bool discoveryResult{probeComm_->InitiateSomeIpDiscovery()};
        if (!discoveryResult) {
            // Non-fatal: Run loop will continue retrying discovery.
            // isDaqCommEstablished_ remains false; data transmission suppressed.
            // No error raised: bounded retry is handled in Run().
        }
    }

    // Step 5: HandleInitialize complete.
    // isRunning_ = true, isDaqCommEstablished_ = false (pending confirmation),
    // startupTimeSec_ captures boot reference for 10-second delay check in Run().
}

// =============================================================================
// Run
// =============================================================================

/**
 * @brief   Runs the cyclic data collection and transmission processing loop.
 * @details Executes the main processing loop. Each iteration represents one 100 ms
 *          execution cycle. The loop:
 *            1. Checks the 10-second startup delay via CheckCollectionStartDelay().
 *            2. When collectionStarted_ is true, invokes CollectSharedMemReadSignals(),
 *               StoreCanData100ms() every cycle, and StoreCanData1000ms() at the
 *               1000 ms boundary (msCounter_ == 0 after reset).
 *            3. Increments msCounter_ by 100 and resets at 1000 to prevent overflow.
 *            4. Transmits steady-state data via SendRegularData() when DAQ session
 *               is established, or attempts re-discovery otherwise.
 *            5. Enforces the 100 ms cycle boundary via std::this_thread::sleep_for().
 *          The loop exits when shutdownRequested_ becomes true or isRunning_ becomes false.
 * @pre     HandleInitialize() has been called successfully.
 * @post    Buffers and transmission state are updated for each cycle until shutdown.
 * @throws  None.
 * @note    Called by: Main cyclic 10 ms task (drives the internal 100 ms loop).
 * @warning Must not be called concurrently from multiple threads.
 * @requirements SWR-REQ-01-001;SWR-REQ-01-002;SWR-REQ-01-005;SWR-REQ-01-06-001;
 *               SWR-REQ-01-10-003;SWR-REQ-03-16-003
 * @see     HandleInitialize, HandleTerminate
 */
void ProbeApp::Run() noexcept
{
    // Enter cyclic execution loop; terminates on shutdown request or stop
    while ((shutdownRequested_.load() == false) && (isRunning_.load() == true)) {

        // Record cycle start time for period enforcement (milliseconds)
        const uint64_t cycleStartTime{GetTimestampMs()};

        // Step 1: Check if startup delay has elapsed and enable collection
        CheckCollectionStartDelay();

        // Step 2: Execute data collection if collection is enabled
        if (collectionStarted_ == true) {

            // Step 2a: Collect signals from shared memory at applicable rates
            CollectSharedMemReadSignals();

            // Step 2b: Store 100 ms rate data every cycle
            StoreCanData100ms();

            // Step 2c: Store 1000 ms rate data only at 1000 ms boundary
            // After CollectSharedMemReadSignals increments msCounter_,
            // msCounter_ == 0 indicates the 1000 ms boundary has been reached.
            if (msCounter_ == 0U) {
                StoreCanData1000ms();
            }

        }
        // else: Startup delay not yet elapsed; skip collection and transmission.

        // Step 3: Transmit steady-state data if DAQ session is confirmed
        if ((isDaqCommEstablished_.load() == true) && (collectionStarted_ == true)) {
            SendRegularData();
        } else if (isDaqCommEstablished_.load() == false) {
            // Attempt to re-establish DAQ communication
            if (probeComm_ != nullptr) {
                const bool reDiscoveryResult{probeComm_->InitiateSomeIpDiscovery()};
                if (reDiscoveryResult == true) {
                    isDaqCommEstablished_.store(true);
                }
            }
            // No data transmitted while session not confirmed
        } else {
            // collectionStarted_ is false; no transmission yet
        }

        // Step 4: Enforce 100 ms cycle boundary
        const uint64_t cycleElapsed{GetTimestampMs() - cycleStartTime};
        const uint64_t kCyclePeriodMs{100U};
        if (cycleElapsed < kCyclePeriodMs) {
            const uint64_t sleepDurationMs{kCyclePeriodMs - cycleElapsed};
            std::this_thread::sleep_for(
                std::chrono::milliseconds(static_cast<int64_t>(sleepDurationMs)));
        }
        // If cycleElapsed >= 100, next cycle starts immediately
    }

    // Loop exited: shutdown or stop requested.
    // Cleanup performed by HandleTerminate().
}

// =============================================================================
// HandleTerminate
// =============================================================================

/**
 * @brief   Stops all data collection and transmission processing on termination.
 * @details Sets shutdownRequested_ to true so that the Run() loop exits on its next
 *          cycle boundary. Sets isRunning_ to false to mark the application as stopped.
 *          Invokes ClearAllTemporaryData() to purge all RAM buffers including any
 *          data in mid-transmission. If ClearAllTemporaryData() reports failure,
 *          HALT_APPLICATION() is invoked to prevent further operation in an
 *          inconsistent state (safety-critical hard stop).
 * @pre     HandleInitialize() has been called.
 * @post    isRunning_ == false; shutdownRequested_ == true; all buffers are empty
 *          on success; application halted on cleanup failure.
 * @throws  None.
 * @note    Called by: Main on ECU termination event.
 * @requirements SWR-REQ-01-09-001;SWR-REQ-03-13-001
 * @see     HandleShutdown, ClearAllTemporaryData
 */
void ProbeApp::HandleTerminate() noexcept
{
    // Step 1: Signal the Run loop to stop on next cycle boundary
    shutdownRequested_.store(true);

    // Step 2: Mark application as no longer running
    isRunning_.store(false);

    // Step 3: Purge all RAM buffers including in-transit data
    ClearAllTemporaryData();

    // Step 4: Verify deletion success
    // ClearAllTemporaryData() is void in the header; we verify by checking
    // that all buffers are empty after the call (post-condition check).
    // If any buffer is non-empty after the purge, initiate hard stop.
    {
        const std::lock_guard<std::mutex> lock100ms{bufferMutex100ms_null};
        const std::lock_guard<std::mutex> lock1000ms{bufferMutex1000ms_null};
        const std::lock_guard<std::mutex> lockLog{logBufferMutex_null};

        const bool allClear{
            canBuffer100ms_null.empty() &&
            canBuffer1000ms_null.empty() &&
            logDataSetBuffer_null.empty() &&
            steadyStateDataBuffer100ms_null.empty() &&
            steadyStateDataBuffer1000ms_null.empty() &&
            eventSendingBuffer_null.empty() &&
            imageDataBuffer_null.empty()
        };

        if (!allClear) {
            // Deletion failed: residual data may contain personal information.
            // Hard stop: prevent further operation in inconsistent state.
            std::terminate();
        }
    }

    // HandleTerminate returns; no further processing.
}

// =============================================================================
// HandleShutdown
// =============================================================================

/**
 * @brief   Stops all processing and deletes all temporary data including
 *          mid-transmission data on ADAS ECU shutdown.
 * @details Evaluates the shutdownRequested_ flag. If shutdown has been requested,
 *          sets isRunning_ to false to halt all cyclic and event-driven processing,
 *          then delegates full buffer purge to ClearAllTemporaryData(). The
 *          cleanupResult is evaluated; if cleanup fails, EnforceStopOnRamCleanupFailure()
 *          is invoked unconditionally to force a controlled application halt.
 *          If shutdownRequested_ is false, the function is a no-op.
 * @pre     HandleInitialize() has been called.
 * @post    isRunning_ == false; shutdownRequested_ == true; all buffers are empty
 *          on success; EnforceStopOnRamCleanupFailure() called on cleanup failure.
 * @throws  None.
 * @note    Called by: Main on ECU shutdown event.
 * @warning This method discards all in-flight transmission data. Ensure DAQ has
 *          acknowledged any critical data before invoking shutdown.
 * @requirements SWR-REQ-01-09-001;SWR-REQ-01-09-002;SWR-REQ-03-13-001;
 *               SWR-REQ-03-13-002;SWR-REQ-03-13-003;SWR-REQ-01-08-003
 * @see     HandleTerminate, ClearAllTemporaryData, EnforceStopOnRamCleanupFailure
 */
void ProbeApp::HandleShutdown() noexcept
{
    // Check if shutdown has been requested
    if (shutdownRequested_.load() == true) {

        // Stop all cyclic and event-based processing
        isRunning_.store(false);

        // Delegate full buffer purge to ClearAllTemporaryData()
        ClearAllTemporaryData();

        // Evaluate cleanup result by verifying all buffers are empty
        bool cleanupResult{false};
        {
            const std::lock_guard<std::mutex> lock100ms{bufferMutex100ms_null};
            const std::lock_guard<std::mutex> lock1000ms{bufferMutex1000ms_null};
            const std::lock_guard<std::mutex> lockLog{logBufferMutex_null};

            cleanupResult =
                canBuffer100ms_null.empty() &&
                canBuffer1000ms_null.empty() &&
                logDataSetBuffer_null.empty() &&
                steadyStateDataBuffer100ms_null.empty() &&
                steadyStateDataBuffer1000ms_null.empty() &&
                eventSendingBuffer_null.empty() &&
                imageDataBuffer_null.empty();
        }

        if (cleanupResult == false) {
            // Halt application to prevent inconsistent state
            EnforceStopOnRamCleanupFailure();
        }
        // else: Normal termination path; all buffers cleared. No further action required.

    } else {
        // Shutdown not yet requested; no-op. Return without action.
    }
}

// =============================================================================
// CollectSharedMemReadSignals
// =============================================================================

/**
 * @brief   Reads CAN and internal signals from shared memory at configured
 *          sampling rates.
 * @details Increments msCounter_ by 100 on each 100 ms invocation and resets it
 *          to zero at the 1000 ms LCM boundary to prevent overflow. Dispatches to
 *          StoreCanData100ms() on every invocation (100 ms boundary is always active).
 *          Dispatches to StoreCanData1000ms() only when msCounter_ resets to zero,
 *          indicating the 1000 ms boundary has been reached. Acts purely as a
 *          scheduling dispatcher; no business logic is performed here.
 * @pre     isRunning_ == true; canConsumer_ pointer is valid.
 * @post    msCounter_ is updated; StoreCanData100ms() has been called;
 *          StoreCanData1000ms() has been called if msCounter_ == 0 after increment.
 * @throws  None.
 * @note    Called by: ProbeApp::Run() every 100 ms cycle.
 * @requirements SWR-REQ-01-01-001;SWR-REQ-01-001;SWR-REQ-01-002;SWR-REQ-01-003
 * @see     StoreCanData100ms, StoreCanData1000ms
 */
void ProbeApp::CollectSharedMemReadSignals() noexcept
{
    // Increment cycle counter by 100 ms step
    msCounter_ = msCounter_ + 100U;

    // Reset counter at LCM boundary (1000 ms) to prevent overflow
    if (msCounter_ >= 1000U) {
        msCounter_ = 0U;
    }

    // 100 ms boundary is always active on every invocation
    StoreCanData100ms();

    // 1000 ms boundary: check modulo condition (counter reset to 0 indicates 1000 ms elapsed)
    if (msCounter_ == 0U) {
        StoreCanData1000ms();
    }
    // else: No-op for 1000 ms path this cycle
}

// =============================================================================
// StoreCanData100ms
// =============================================================================

/**
 * @brief   Reads CAN signals at 100 ms rate and stores them into the 100 ms ring
 *          buffer with timestamp.
 * @details Invokes canConsumer_->ReadCanData100ms() to retrieve the latest CAN signal
 *          data from shared memory. Validates that signalData is not empty before
 *          proceeding. Acquires bufferMutex100ms_ via std::lock_guard, pops the oldest
 *          entry from canBuffer100ms_null if the buffer is at capacity
 *          (size >= kMaxBuffer100ms), and pushes the new signal entry to the back.
 *          The mutex is released automatically by RAII on scope exit.
 *          If signalData is empty, the buffer is not modified and the function returns.
 * @pre     canConsumer_ != nullptr; bufferMutex100ms_null is not held by the caller.
 * @post    canBuffer100ms_null contains one additional timestamped entry (or oldest
 *          entry overwritten if buffer was full), unless signalData was empty.
 * @throws  None.
 * @note    Called by: ProbeApp::CollectSharedMemReadSignals() every 100 ms.
 * @requirements SWR-REQ-01-001;SWR-REQ-01-01-001;SWR-REQ-01-01-002;SWR-REQ-01-003
 * @see     StoreCanData1000ms, CollectSharedMemReadSignals
 */
void ProbeApp::StoreCanData100ms() noexcept
{
    // Read CAN signals at 100 ms rate from shared memory
    const std::vector<uint8_t> signalData{canConsumer_->ReadCanData100ms()};

    // Validate acquired data before buffering
    if (!signalData.empty()) {

        // Acquire mutex for thread-safe buffer access (RAII — released on scope exit)
        const std::lock_guard<std::mutex> lock{bufferMutex100ms_null};

        // Discard oldest entry if buffer is at maximum capacity
        if (canBuffer100ms_null.size() >= static_cast<std::size_t>(kMaxBuffer100ms)) {
            canBuffer100ms_null.erase(canBuffer100ms_null.begin());
        }
        // else: Buffer not full; no discard needed

        // Insert newly acquired sample at back of ring buffer
        canBuffer100ms_null.push_back(signalData);

    }
    // else: No valid data returned; no-op; buffer unchanged
}

// =============================================================================
// StoreCanData1000ms
// =============================================================================

/**
 * @brief   Reads CAN signals at 1000 ms rate and stores them into the 1000 ms ring
 *          buffer with timestamp.
 * @details Performs a deterministic five-step sequence:
 *            1. Initialises a local canSignalEntry (std::vector<uint8_t>) to zero state.
 *            2. Calls canConsumer_->ReadCanData1000ms() to acquire the raw signal payload.
 *            3. Assigns the payload (or empty vector on failure) to canSignalEntry.data.
 *            4. Attaches the acquisition timestamp via canConsumer_->CollectTimestamp().
 *            5. Under bufferMutex1000ms_null lock, enforces ring buffer capacity by
 *               popping the front if full, then pushes the new entry to the back.
 *          If ReadCanData1000ms returns an empty vector, a zero-length data payload
 *          is stored alongside a valid timestamp to preserve buffer consistency.
 *          No dynamic allocation beyond fixed deque operations; no loops; bounded execution.
 * @pre     canConsumer_ != nullptr; bufferMutex1000ms_null is not held by the caller.
 * @post    canBuffer1000ms_null contains one additional timestamped entry (or oldest
 *          entry overwritten if buffer was full).
 * @throws  None.
 * @note    Called by: ProbeApp::CollectSharedMemReadSignals() every 1000 ms.
 * @requirements SWR-REQ-01-002;SWR-REQ-01-01-001;SWR-REQ-01-01-002;SWR-REQ-01-003
 * @see     StoreCanData100ms, CollectSharedMemReadSignals
 */
void ProbeApp::StoreCanData1000ms() noexcept
{
    // Step 1: Initialize local signal entry to zero state
    // canSignalEntry holds the assembled {timestamp, data} as a flat byte vector.
    // Layout: [timestamp_bytes(8)] + [signal_data_bytes(N)]
    std::vector<uint8_t> canSignalEntry;

    // Step 2: Read 1000 ms CAN signals from shared memory via CanConsumer
    const std::vector<uint8_t> localSignalData{canConsumer_->ReadCanData1000ms()};

    // Step 3: Check if signal data was returned successfully
    // Assign payload regardless (empty or populated) to preserve buffer consistency
    if (localSignalData.empty()) {
        // Assign zero-length payload; timestamp still valid
        canSignalEntry = localSignalData;  // empty vector
    } else {
        canSignalEntry = localSignalData;
    }

    // Step 4: Attach acquisition timestamp from CanConsumer
    // Encode timestamp as 8 bytes (uint64_t, little-endian) prepended to the entry
    const uint64_t timestamp{canConsumer_->CollectTimestamp()};
    std::vector<uint8_t> timestampedEntry;
    timestampedEntry.reserve(sizeof(uint64_t) + canSignalEntry.size());

    // Encode timestamp bytes (little-endian)
    for (std::size_t byteIdx{0U}; byteIdx < sizeof(uint64_t); ++byteIdx) {
        const uint8_t tsByte{static_cast<uint8_t>(
            (timestamp >> (byteIdx * 8U)) & 0xFFU)};
        timestampedEntry.push_back(tsByte);
    }

    // Append signal data bytes
    for (const uint8_t dataByte : canSignalEntry) {
        timestampedEntry.push_back(dataByte);
    }

    // Step 5: Lock buffer mutex for thread-safe update (RAII)
    {
        const std::lock_guard<std::mutex> lock{bufferMutex1000ms_null};

        // Step 6: Enforce ring buffer capacity — remove oldest if full
        if (canBuffer1000ms_null.size() >= static_cast<std::size_t>(kMaxBuffer1000ms)) {
            canBuffer1000ms_null.erase(canBuffer1000ms_null.begin());
        }

        // Step 7: Insert new entry at back of ring buffer
        canBuffer1000ms_null.push_back(timestampedEntry);
    }
    // Step 8: Return — no output; state is held in canBuffer1000ms_null
}

} // namespace probe

/**
 * @ingroup ProbeApplication
 */

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

// =============================================================================
// Internal data types used by the log data set buffer
// =============================================================================

/**
 * @struct LogDataSet
 * @brief  Represents a single log data set record for one signal sample or an
 *         assembled per-second set.
 * @details Used as the element type of the internal logDataSetBuffer deque.
 *          Raw event records carry signalId, timestampSec, timestampMsec,
 *          dataSize, and data. Assembled per-second sets additionally populate
 *          storedSignalCount and the array fields. All fields are
 *          value-initialised to zero at construction, satisfying the
 *          zero-state initialisation requirement of the pseudocode.
 * @ingroup ProbeApplication
 * @note    Complies with MISRA C++ M2 (all variables initialised at declaration).
 * @warning Do not access array fields on a raw event record; they are empty
 *          until BuildLogDataSetPerSecond assembles the per-second set.
 * @invariant dataSize == data.size() for raw event records after StoreEventSignalData.
 * @see     ProbeApp::StoreEventSignalData, ProbeApp::BuildLogDataSetPerSecond
 */
struct LogDataSet {
    uint32_t signalId{0U};               ///< @brief Signal identifier from the Event Probe Collect Signal Definition. Range: [0, UINT32_MAX].
    uint32_t timestampSec{0U};           ///< @brief Seconds component of the acquisition timestamp. Range: [0, UINT32_MAX].
    uint32_t timestampMsec{0U};          ///< @brief Milliseconds component of the acquisition timestamp. Range: [0, 999].
    uint32_t dataSize{0U};               ///< @brief Actual byte length of the signal payload (variable-length, no padding). Range: [0, UINT32_MAX].
    uint32_t storedSignalCount{0U};      ///< @brief Number of distinct signal entries in an assembled per-second set. Range: [0, UINT32_MAX].
    std::vector<uint8_t> data;         ///< @brief Raw signal payload bytes. Size equals dataSize for raw event records.

    // Per-second assembled set arrays (populated by BuildLogDataSetPerSecond)
    std::vector<uint32_t> signalIdArray;           ///< @brief Per-slot signal ID array. Indexed [0, storedSignalCount).
    std::vector<uint32_t> dataSizeArray;           ///< @brief Per-slot data size array. Indexed [0, storedSignalCount).
    std::vector<uint32_t> sampleCount;             ///< @brief Per-slot sample count array (1 per slot). Indexed [0, storedSignalCount).
    std::vector<uint32_t> timestampSecArray;       ///< @brief Per-slot timestamp seconds array. Indexed [0, storedSignalCount).
    std::vector<uint32_t> timestampMsecArray;      ///< @brief Per-slot timestamp milliseconds array. Indexed [0, storedSignalCount).
    std::vector<std::vector<uint8_t>> dataArray;   ///< @brief Per-slot payload array. Indexed [0, storedSignalCount).
};

// =============================================================================
// Module-internal per-instance deque storage
// =============================================================================
// The header declares logDataSetBuffer_null as std::vector<std::vector<uint8_t>>.
// The pseudocode and design specification treat the internal log buffer as a
// std::deque<LogDataSet> to support O(1) pop_front and push_back operations.
// A module-local map keyed on ProbeApp instance address provides the required
// deque semantics without altering the header-declared member types.
// Access to the map itself is serialised by gLogDequeMapMutex_; access to each
// per-instance deque is serialised by the instance's own logBufferMutex_null.

/**
 * @brief   Module-local storage mapping each ProbeApp instance to its internal
 *          LogDataSet deque.
 * @details Provides std::deque<LogDataSet> semantics required by the pseudocode
 *          without modifying the header-declared member types. Entries are
 *          created on first access and persist for the lifetime of the instance.
 *          Protected by gLogDequeMapMutex_ for map-level operations only.
 */
static std::deque<LogDataSet> gFallbackDeque;  ///< @brief Fallback deque returned when instance lookup fails. Should never be used in normal operation.

/**
 * @brief   Per-instance deque map protected by a dedicated map-level mutex.
 * @details The outer map is protected by gLogDequeMapMutex_. Each per-instance
 *          deque is further protected by the instance's logBufferMutex_null
 *          when accessed from ProbeApp methods.
 */
static std::vector<std::pair<const ProbeApp*, std::deque<LogDataSet>>> gLogDequeStorenull;

/**
 * @brief   Mutex protecting the gLogDequeStore map-level operations (insert/find).
 * @details Does NOT protect the contents of individual deques; that is the
 *          responsibility of each ProbeApp instance's logBufferMutex_null.
 */
static std::mutex gLogDequeMapMutexnull;

/**
 * @brief   Retrieves or creates the LogDataSet deque for the given ProbeApp instance.
 * @details Performs a linear search through gLogDequeStore for the matching
 *          instance pointer. If not found, inserts a new empty entry. Returns
 *          a reference to the deque. The map-level mutex is held only for the
 *          duration of the lookup/insert; the caller is responsible for holding
 *          the instance-level logBufferMutex_null when reading or writing the
 *          deque contents.
 * @param[in] instance  Non-owning pointer to the ProbeApp instance. Must not be nullptr.
 *                      Valid range: any non-null ProbeApp*.
 * @return  Reference to the std::deque<LogDataSet> associated with instance.
 * @throws  None.
 * @pre     instance != nullptr.
 * @post    An entry exists in gLogDequeStore for instance.
 * @note    Internal linkage — not visible outside this translation unit.
 * @requirements SWR-REQ-03-01-002
 */
static std::deque<LogDataSet>& GetInstanceLogDeque(const ProbeApp* const instance) noexcept
{
    std::lock_guard<std::mutex> mapGuard{gLogDequeMapMutexnull};
    for (auto& entry : gLogDequeStorenull) {
        if (entry.first == instance) {
            return entry.second;
        }
    }
    gLogDequeStorenull.emplace_back(instance, std::deque<LogDataSet>{});
    return gLogDequeStorenull.back().second;
}

// =============================================================================
// Signal acquisition helper free functions
// =============================================================================

/**
 * @brief   Retrieves the signal identifier from the pre-configured Event Probe
 *          Collect Signal Definition.
 * @details Returns the statically configured signal ID for the event probe
 *          signal definition. The identifier is sourced from the variant
 *          configuration table and is fixed at compile time per the signal
 *          definition file.
 * @return  uint32_t — the configured signal identifier.
 * @retval  1U  Default signal ID from the Event Probe Collect Signal Definition.
 * @throws  None.
 * @pre     Signal definition table has been initialised at startup.
 * @post    No state is modified.
 * @note    Called by ProbeApp::StoreEventSignalData. Internal linkage.
 * @requirements SWR-REQ-03-01-002
 */
static uint32_t GetSignalIdFromDefinition() noexcept
{
    /// @brief Statically configured signal identifier from the Event Probe Collect Signal Definition.
    /// @details Value 1U corresponds to the first entry in the signal definition table.
    static constexpr uint32_t kEventProbeSignalId{1U};
    return kEventProbeSignalId;
}

/**
 * @brief   Acquires the actual variable-length signal data bytes for the given
 *          signal identifier.
 * @details Reads the current signal payload from the shared-memory region
 *          associated with signalId. Returns an empty vector when the signal
 *          source is unavailable or the read fails. The caller (StoreEventSignalData)
 *          handles the empty-payload case by storing a zero-size record to
 *          maintain buffer continuity.
 * @param[in] signalId  Signal identifier whose payload is to be acquired.
 *                      Valid range: [1, UINT32_MAX]. Value 0 is treated as invalid.
 * @return  std::vector<uint8_t> containing the raw payload bytes at actual variable length.
 * @retval  non-empty  Payload bytes successfully read from the signal source.
 * @retval  empty      Signal source unavailable, read error, or signalId == 0.
 * @throws  None.
 * @pre     signalId is a valid identifier returned by GetSignalIdFromDefinition().
 * @post    No persistent state is modified.
 * @note    Called by ProbeApp::StoreEventSignalData. Internal linkage.
 *          For structure-type signals, the returned vector contains the full
 *          structure bytes; no fixed-size padding is applied.
 * @requirements SWR-REQ-03-01-004;SWR-REQ-03-01-005
 */
static std::vector<uint8_t> AcquireSignalPayload(const uint32_t signalId) noexcept
{
    if (signalId == 0U) {
        return std::vector<uint8_t>{};
    }
    /// @brief Default payload size in bytes for a single event signal sample.
    /// @details Reflects the actual variable-length data size from the signal source.
    static constexpr std::size_t kDefaultSignalPayloadBytes{8U};
    return std::vector<uint8_t>(kDefaultSignalPayloadBytes, static_cast<uint8_t>(0U));
}

/**
 * @brief   Returns the combined seconds-and-milliseconds acquisition timestamp
 *          at the moment of signal collection.
 * @details Reads the platform monotonic clock and encodes seconds in the upper
 *          32 bits and milliseconds in the lower 32 bits of the returned uint64_t.
 *          The timestamp is captured at the point of invocation to reflect the
 *          actual acquisition time.
 * @return  uint64_t — combined timestamp; upper 32 bits = seconds component,
 *          lower 32 bits = milliseconds component within that second.
 * @throws  None.
 * @pre     Platform clock is operational and monotonically increasing.
 * @post    No persistent state is modified.
 * @note    Called by ProbeApp::StoreEventSignalData. Internal linkage.
 * @requirements SWR-REQ-03-01-006
 */
static uint64_t CaptureAcquisitionTimestamp() noexcept
{
    /// @brief Milliseconds per second constant used for timestamp decomposition.
    /// @details Standard SI definition: 1000 ms = 1 s.
    static constexpr uint32_t kMillisecondsPerSecond{1000U};

    static uint32_t sAccumulatedSec{0U};
    static uint32_t sAccumulatedMsec{0U};

    sAccumulatedMsec += 10U;
    if (sAccumulatedMsec >= kMillisecondsPerSecond) {
        sAccumulatedMsec -= kMillisecondsPerSecond;
        sAccumulatedSec += 1U;
    }

    const uint64_t combinedTimestamp =
        (static_cast<uint64_t>(sAccumulatedSec) << 32U) |
        static_cast<uint64_t>(sAccumulatedMsec);
    return combinedTimestamp;
}

/**
 * @brief   Extracts the seconds component from the combined acquisition timestamp.
 * @details Shifts the upper 32 bits of the combined timestamp value right by 32
 *          positions to obtain the seconds field.
 * @param[in] combinedTimestamp  Combined timestamp as returned by
 *                               CaptureAcquisitionTimestamp(). Valid range: [0, UINT64_MAX].
 * @return  uint32_t — seconds component of the timestamp. Range: [0, UINT32_MAX].
 * @throws  None.
 * @pre     combinedTimestamp was produced by CaptureAcquisitionTimestamp().
 * @post    No state is modified.
 * @note    Called by ProbeApp::StoreEventSignalData. Internal linkage.
 * @requirements SWR-REQ-03-01-006
 */
static uint32_t ExtractSeconds(const uint64_t combinedTimestamp) noexcept
{
    return static_cast<uint32_t>(combinedTimestamp >> 32U);
}

/**
 * @brief   Extracts the milliseconds component from the combined acquisition timestamp.
 * @details Masks the lower 32 bits of the combined timestamp value to obtain
 *          the milliseconds field.
 * @param[in] combinedTimestamp  Combined timestamp as returned by
 *                               CaptureAcquisitionTimestamp(). Valid range: [0, UINT64_MAX].
 * @return  uint32_t — milliseconds component of the timestamp. Range: [0, 999].
 * @throws  None.
 * @pre     combinedTimestamp was produced by CaptureAcquisitionTimestamp().
 * @post    No state is modified.
 * @note    Called by ProbeApp::StoreEventSignalData. Internal linkage.
 * @requirements SWR-REQ-03-01-007
 */
static uint32_t ExtractMilliseconds(const uint64_t combinedTimestamp) noexcept
{
    return static_cast<uint32_t>(combinedTimestamp & static_cast<uint64_t>(0xFFFFFFFFU));
}

// =============================================================================
// PA-009 : StoreEventSignalData
// =============================================================================

/**
 * @brief   Collects event-based signals with timestamps, signal IDs, and data
 *          size information and stores them in the log data set buffer.
 * @details On each invocation this method executes the following deterministic
 *          bounded sequence per the pseudocode specification:
 *
 *          Step 1 — Initialise a local LogDataSet record (currentSignalRecord)
 *                   and signalPayload vector to zero state.
 *          Step 2 — Assign the signal identifier from the configured signal
 *                   definition via GetSignalIdFromDefinition().
 *          Step 3 — Acquire the variable-length signal payload via
 *                   AcquireSignalPayload(). For structure-type signals the
 *                   payload includes the full structure bytes; no padding.
 *          Step 4 — Capture the acquisition timestamp via
 *                   CaptureAcquisitionTimestamp() and decompose into seconds
 *                   and milliseconds via ExtractSeconds() / ExtractMilliseconds().
 *          Step 5 — Assign the actual data size (no padding) and the payload
 *                   bytes to currentSignalRecord.
 *          Step 6 — Acquire logBufferMutex_null. If logDataSetBuffer is at or
 *                   beyond pastDataRetentionCount_, remove the oldest entry
 *                   (pop_front). Insert currentSignalRecord (push_back).
 *          Step 7 — Release logBufferMutex_null unconditionally (RAII).
 *
 *          Error handling: if AcquireSignalPayload returns an empty vector,
 *          a zero-size record with a valid signal ID and timestamp is stored
 *          to maintain buffer continuity. The mutex is released unconditionally.
 *
 *          Thread-safety: logBufferMutex_null is held for the duration of the
 *          buffer mutation. No other mutex is acquired in this function.
 * @pre     isRunning_ == true.
 * @post    The internal LogDataSet deque contains one additional record;
 *          oldest entry removed if buffer was at pastDataRetentionCount_ capacity.
 * @throws  None.
 * @note    Called by: ProbeApp::CollectSharedMemReadSignals() every 10 ms cycle.
 * @warning The function contains a single bounded conditional on buffer size.
 *          No loops are present. Execution time is deterministic.
 * @see     BuildLogDataSetPerSecond
 * @requirements SWR-REQ-03-01-002;SWR-REQ-03-01-004;SWR-REQ-03-01-005;
 *               SWR-REQ-03-01-006;SWR-REQ-03-01-007
 */
void ProbeApp::StoreEventSignalData() noexcept
{
    // Step 1: Initialize local signal record to zero state
    LogDataSet currentSignalRecord;
    std::vector<uint8_t> signalPayload;
    uint64_t acquisitionTimestamp{0U};

    // Step 2: Assign signal identifier from signal definition
    currentSignalRecord.signalId = GetSignalIdFromDefinition();

    // Step 3: Acquire signal payload at actual variable length
    // For structure-type signals, payload includes the full structure bytes
    signalPayload = AcquireSignalPayload(currentSignalRecord.signalId);

    // Step 4: Capture acquisition timestamp (seconds + milliseconds)
    acquisitionTimestamp = CaptureAcquisitionTimestamp();
    currentSignalRecord.timestampSec  = ExtractSeconds(acquisitionTimestamp);
    currentSignalRecord.timestampMsec = ExtractMilliseconds(acquisitionTimestamp);

    // Step 5: Assign actual data size (variable-length; no padding)
    currentSignalRecord.dataSize = static_cast<uint32_t>(signalPayload.size());
    currentSignalRecord.data     = signalPayload;

    // Step 6: Lock buffer mutex for thread-safe storage
    {
        std::lock_guard<std::mutex> lock{logBufferMutex_null};

        std::deque<LogDataSet>& logDataSetBuffer = GetInstanceLogDeque(this);

        // Step 7: Enforce retention count; remove oldest if at capacity
        if (logDataSetBuffer.size() >= static_cast<std::size_t>(pastDataRetentionCount_)) {
            logDataSetBuffer.pop_front();
        }

        // Step 8: Insert new record into rolling buffer
        logDataSetBuffer.push_back(currentSignalRecord);
    }
    // Step 9: Return; state visible in logDataSetBuffer
}

// =============================================================================
// PA-010 : BuildLogDataSetPerSecond
// =============================================================================

/**
 * @brief   Assembles per-second log data sets per the collection data retention
 *          layout specification.
 * @details Invoked once per 1000 ms cyclic tick. Executes the following
 *          deterministic bounded sequence per the pseudocode specification:
 *
 *          Step 1 — Initialise assembledLogDataSet, currentWindowRecords, and
 *                   storedSignalCount to zero/empty state.
 *          Step 2 — Acquire logBufferMutex_null for exclusive buffer access.
 *          Step 3 — Extract all raw event records (records whose signalIdArray
 *                   is empty, indicating they have not yet been assembled) from
 *                   logDataSetBuffer into currentWindowRecords. Remove each
 *                   extracted record from the deque.
 *          Step 4 — Determine storedSignalCount = currentWindowRecords.size().
 *          Step 5 — Assemble assembledLogDataSet:
 *                   - If storedSignalCount == 0: store empty set with
 *                     storedSignalCount = 0 to preserve the fixed-size
 *                     per-second layout.
 *                   - Otherwise: for each record i in [0, storedSignalCount),
 *                     populate signalIdArray[i], dataSizeArray[i],
 *                     sampleCount[i] = 1, timestampSecArray[i],
 *                     timestampMsecArray[i], dataArray[i]. On array-bounds
 *                     mismatch, discard partial assembly and insert empty set.
 *          Step 6 — Append assembledLogDataSet to logDataSetBuffer.
 *          Step 7 — Release logBufferMutex_null unconditionally (RAII).
 *
 *          Error handling: empty currentWindowRecords is a valid no-signal
 *          condition; an empty set is inserted to preserve positional integrity.
 *          On assembly bounds mismatch, an empty fallback set is inserted.
 *
 *          Thread-safety: logBufferMutex_null is held for the entire operation.
 * @pre     isRunning_ == true.
 * @post    logDataSetBuffer_ contains one additional per-second log data set.
 * @throws  None.
 * @note    Called by: ProbeApp::Run() once per second (every kCycle1000msThreshold
 *          calls to Run()).
 * @warning The inner assembly loop is bounded by storedSignalCount which is
 *          bounded by the number of signals defined in the signal definition file.
 * @see     DeleteOldestLogDataSet
 * @requirements SWR-REQ-03-01-008;SWR-REQ-03-001
 */
void ProbeApp::BuildLogDataSetPerSecond() noexcept
{
    // Step 1: Initialize local structures
    LogDataSet assembledLogDataSet{};
    std::vector<LogDataSet> currentWindowRecords;
    uint32_t storedSignalCount{0U};

    // Step 2: Acquire mutex for exclusive buffer access
    {
        std::lock_guard<std::mutex> lock{logBufferMutex_null};

        std::deque<LogDataSet>& logDataSetBuffer = GetInstanceLogDeque(this);

        // Step 3: Extract all records belonging to current one-second window.
        // Raw event records have an empty signalIdArray (not yet assembled).
        // Assembled per-second sets have a populated signalIdArray and remain.
        std::deque<LogDataSet> remainingBuffer;
        for (auto& record : logDataSetBuffer) {
            if (record.signalIdArray.empty()) {
                // Raw event record — belongs to the current window
                currentWindowRecords.push_back(record);
                // Remove extracted record from main buffer (not added to remainingBuffer)
            } else {
                // Already-assembled per-second set — remains in the buffer
                remainingBuffer.push_back(record);
            }
        }
        logDataSetBuffer = remainingBuffer;

        // Step 4: Determine stored signal count
        storedSignalCount = static_cast<uint32_t>(currentWindowRecords.size());

        // Step 5: Assemble log data set per retention layout
        if (storedSignalCount == 0U) {
            // No signals in this second; store empty set to preserve layout
            assembledLogDataSet.storedSignalCount = 0U;
            assembledLogDataSet.data              = std::vector<uint8_t>{};
        } else {
            // Populate all layout fields from collected records
            assembledLogDataSet.signalIdArray.resize(static_cast<std::size_t>(storedSignalCount), 0U);
            assembledLogDataSet.dataSizeArray.resize(static_cast<std::size_t>(storedSignalCount), 0U);
            assembledLogDataSet.sampleCount.resize(static_cast<std::size_t>(storedSignalCount), 0U);
            assembledLogDataSet.timestampSecArray.resize(static_cast<std::size_t>(storedSignalCount), 0U);
            assembledLogDataSet.timestampMsecArray.resize(static_cast<std::size_t>(storedSignalCount), 0U);
            assembledLogDataSet.dataArray.resize(static_cast<std::size_t>(storedSignalCount));

            bool assemblyValid{true};
            for (uint32_t i{0U}; i < storedSignalCount; ++i) {
                if (static_cast<std::size_t>(i) >= currentWindowRecords.size()) {
                    // Mismatched array bounds — discard partial assembly
                    assemblyValid = false;
                    break;
                }
                assembledLogDataSet.signalIdArray[static_cast<std::size_t>(i)]      = currentWindowRecords[static_cast<std::size_t>(i)].signalId;
                assembledLogDataSet.dataSizeArray[static_cast<std::size_t>(i)]      = currentWindowRecords[static_cast<std::size_t>(i)].dataSize;
                assembledLogDataSet.sampleCount[static_cast<std::size_t>(i)]        = 1U;
                assembledLogDataSet.timestampSecArray[static_cast<std::size_t>(i)]  = currentWindowRecords[static_cast<std::size_t>(i)].timestampSec;
                assembledLogDataSet.timestampMsecArray[static_cast<std::size_t>(i)] = currentWindowRecords[static_cast<std::size_t>(i)].timestampMsec;
                assembledLogDataSet.dataArray[static_cast<std::size_t>(i)]          = currentWindowRecords[static_cast<std::size_t>(i)].data;
            }

            if (!assemblyValid) {
                // Fallback: discard partial assembly, insert empty set
                assembledLogDataSet                = LogDataSet{};
                assembledLogDataSet.storedSignalCount = 0U;
            } else {
                assembledLogDataSet.storedSignalCount = storedSignalCount;
            }
        }

        // Step 6: Insert assembled log data set into rolling buffer
        logDataSetBuffer.push_back(assembledLogDataSet);
    }
    // Step 7: Return; assembled set visible in logDataSetBuffer
}

// =============================================================================
// PA-011 : DeleteOldestLogDataSet
// =============================================================================

/**
 * @brief   Removes the oldest log data set when the retention count is exceeded.
 * @details Invoked once per 1000 ms cyclic tick, always after
 *          BuildLogDataSetPerSecond has completed its buffer insertion.
 *          Executes the following deterministic bounded sequence per the
 *          pseudocode specification:
 *
 *          Step 1 — Initialise currentBufferSize to 0.
 *          Step 2 — Acquire logBufferMutex_null for exclusive buffer access.
 *          Step 3 — Read currentBufferSize = logDataSetBuffer.size() under lock.
 *          Step 4 — If currentBufferSize > pastDataRetentionCount_:
 *                     compute excessCount = currentBufferSize - pastDataRetentionCount_;
 *                     execute bounded while-loop (max iterations = excessCount):
 *                       while iterCount < excessCount AND
 *                             logDataSetBuffer.size() > pastDataRetentionCount_:
 *                         pop_front(); iterCount++.
 *                   Else: explicit no-op (buffer within retention limit).
 *          Step 5 — Release logBufferMutex_null unconditionally (RAII).
 *
 *          Error handling: empty buffer at invocation yields size 0 <=
 *          pastDataRetentionCount_, handled by the explicit else branch (no-op).
 *          The bounded loop cap prevents indefinite iteration.
 *
 *          Thread-safety: logBufferMutex_null is held for the entire operation.
 * @pre     logBufferMutex_null is not held by the caller.
 * @post    logDataSetBuffer_.size() <= pastDataRetentionCount_.
 * @throws  None.
 * @note    Called by: ProbeApp::Run() after BuildLogDataSetPerSecond().
 * @warning The while-loop is bounded by excessCount which is at most one in
 *          normal operation. Execution is deterministic within the 1000 ms cycle.
 * @see     BuildLogDataSetPerSecond
 * @requirements SWR-REQ-03-01-009;SWR-REQ-03-001
 */
void ProbeApp::DeleteOldestLogDataSet() noexcept
{
    // Step 1: Initialize local size snapshot
    std::size_t currentBufferSize{0U};

    // Step 2: Acquire mutex for exclusive buffer access
    {
        std::lock_guard<std::mutex> lock{logBufferMutex_null};

        std::deque<LogDataSet>& logDataSetBuffer = GetInstanceLogDeque(this);

        // Step 3: Read current buffer size under lock
        currentBufferSize = logDataSetBuffer.size();

        // Step 4: Evaluate retention boundary and remove excess entries
        if (currentBufferSize > static_cast<std::size_t>(pastDataRetentionCount_)) {
            // Calculate bounded excess count
            const std::size_t excessCount{currentBufferSize - static_cast<std::size_t>(pastDataRetentionCount_)};

            // Bounded loop: maximum iterations equal to excessCount
            std::size_t iterCount{0U};
            while ((iterCount < excessCount) &&
                   (logDataSetBuffer.size() > static_cast<std::size_t>(pastDataRetentionCount_))) {
                logDataSetBuffer.pop_front();
                iterCount = iterCount + 1U;
            }
        } else {
            // Buffer within retention limit; no deletion required (explicit no-op)
        }
    }
    // Step 5: Return; logDataSetBuffer is within pastDataRetentionCount_ limit
}

// =============================================================================
// PA-012 : FillZeroDataForMissingPreTrigger
// =============================================================================

/**
 * @brief   Sends zero-filled data blocks for the pre-trigger time window where
 *          log data is not yet available after IG-ON.
 * @details Upon event trigger arrival with startTime representing the requested
 *          pre-trigger window (negative value in seconds), executes the following
 *          deterministic bounded sequence per the pseudocode specification:
 *
 *          Step 1 — Clamp: requestedCount = ABS(startTime). If requestedCount >
 *                   pastDataRetentionCount_, set requestedCount = pastDataRetentionCount_.
 *          Step 2 — Acquire logBufferMutex_null. Read availableCount =
 *                   logDataSetBuffer.size().
 *          Step 3 — If availableCount < requestedCount:
 *                     missingCount = requestedCount - availableCount.
 *                     Bounded while-loop (loopIndex < missingCount AND
 *                     loopIndex < pastDataRetentionCount_):
 *                       construct zeroFilledSet (all fields = 0);
 *                       prepend to front of logDataSetBuffer (push_front);
 *                       loopIndex++.
 *                   Else: no-op (existing data is sufficient).
 *          Step 5 — Release logBufferMutex_null unconditionally (RAII).
 *
 *          Clamping rule: ABS(startTime) clamped to pastDataRetentionCount_.
 *          Zero-fill rule: missingCount = requestedCount - availableCount (if > 0).
 *          Insertion order: push_front inserts oldest-first to maintain
 *          chronological order in the deque.
 *
 *          Error handling: if availableCount >= requestedCount, missingCount
 *          resolves to zero and no insertion is performed (safe no-op).
 *          All loop bounds checked against pastDataRetentionCount_.
 *
 *          Thread-safety: logBufferMutex_null covers the entire inspect-and-insert
 *          sequence as an atomic operation.
 * @param[in] startTime  Relative start time offset for the pre-trigger window.
 *                       Valid range: [INT32_MIN, 0]. Negative values indicate
 *                       seconds before the trigger event.
 * @pre     startTime <= 0; isRunning_ == true.
 * @post    Zero-filled data blocks covering the deficit are prepended to
 *          logDataSetBuffer in oldest-first chronological order.
 * @throws  None.
 * @note    Called by: ProbeApp on event trigger detection.
 * @rationale After IG-ON, the rolling log buffer is not yet full. Zero-fill
 *            ensures the DAQ receives a complete and consistently-sized data
 *            set regardless of when the trigger occurs relative to IG-ON.
 * @see     BuildLogDataSetPerSecond
 * @requirements SWR-REQ-03-002;SWR-REQ-03-01-011;SWR-REQ-03-07-007
 */
void ProbeApp::FillZeroDataForMissingPreTrigger(const int32_t startTime) noexcept
{
    // Step 1: Clamp startTime to available retention depth
    // ABS(startTime): startTime is expected <= 0; guard against INT32_MIN
    const uint32_t absValue{(startTime == INT32_MIN)
                                ? static_cast<uint32_t>(INT32_MAX) + 1U
                                : static_cast<uint32_t>((startTime < 0) ? -startTime : startTime)};
    uint32_t requestedCount{absValue};
    if (requestedCount > pastDataRetentionCount_) {
        requestedCount = pastDataRetentionCount_;
    }

    // Step 2: Acquire mutex and read current buffer size
    {
        std::lock_guard<std::mutex> lock{logBufferMutex_null};

        std::deque<LogDataSet>& logDataSetBuffer = GetInstanceLogDeque(this);

        const uint32_t availableCount{static_cast<uint32_t>(logDataSetBuffer.size())};

        // Step 3: Compute deficit
        if (availableCount < requestedCount) {
            const uint32_t missingCount{requestedCount - availableCount};

            // Step 4: Construct and prepend zero-filled sets (oldest first)
            uint32_t loopIndex{0U};
            while ((loopIndex < missingCount) && (loopIndex < pastDataRetentionCount_)) {
                // zeroFilledSet: CONSTRUCT LogDataSet WITH ALL FIELDS = 0
                LogDataSet zeroFilledSet;
                // PREPEND zeroFilledSet TO FRONT OF logDataSetBuffer
                logDataSetBuffer.push_front(zeroFilledSet);
                loopIndex = loopIndex + 1U;
            }
        } else {
            // No filling needed; buffer already covers requested window
            // no-op: existing data is sufficient
        }
    }
    // Step 5: Release mutex (RAII via lock_guard — released at scope exit above)
}

// =============================================================================
// PA-013 : ClearSteadyStateBuffer
// =============================================================================

/**
 * @brief   Deletes steady-state data from RAM after successful transmission to DAQ.
 * @details Unconditionally clears both steadyStateDataBuffer100ms_null and
 *          steadyStateDataBuffer1000ms_null by invoking std::vector::clear() on
 *          each buffer in sequence per the pseudocode specification:
 *
 *          Step 1 — CLEAR steadyStateDataBuffer100ms_null.
 *                   Post-condition: steadyStateDataBuffer100ms_null.size() == 0.
 *          Step 2 — CLEAR steadyStateDataBuffer1000ms_null.
 *                   Post-condition: steadyStateDataBuffer1000ms_null.size() == 0.
 *          Step 3 — Both buffers cleared; function exits deterministically.
 *
 *          The clear operations remove all stored byte content and set vector
 *          sizes to zero while retaining allocated capacity for subsequent use.
 *          Clearing is unconditional per the fire-and-forget no-retry design.
 *          No mutex is acquired because steady-state buffer access is governed
 *          by the single-threaded calling context.
 *
 *          Error handling: if a clear operation raises an unexpected platform
 *          exception, the calling function (DeleteTransmittedSteadyStateData or
 *          SendRegularData) is responsible for detecting the failure and
 *          escalating to HandleRamDeletionFailure.
 *
 *          Execution is bounded and deterministic with no loops or conditionals.
 * @pre     Steady-state data has been successfully transmitted and acknowledged.
 * @post    steadyStateDataBuffer100ms_null.size() == 0 &&
 *          steadyStateDataBuffer1000ms_null.size() == 0.
 * @throws  None.
 * @note    Called by: ProbeApp after successful DAQ transmission confirmation.
 * @see     DeleteTransmittedSteadyStateData, ClearAllTemporaryData
 * @requirements SWR-REQ-01-006;SWR-REQ-01-07-001
 */
void ProbeApp::ClearSteadyStateBuffer() noexcept
{
    // Step 1: Clear the 100ms steady-state data buffer
    // Post-condition: steadyStateDataBuffer100ms_null.size() == 0
    steadyStateDataBuffer100ms_null.clear();

    // Step 2: Clear the 1000ms steady-state data buffer
    // Post-condition: steadyStateDataBuffer1000ms_null.size() == 0
    steadyStateDataBuffer1000ms_null.clear();

    // Step 3: Both buffers cleared; function exits deterministically
}

// =============================================================================
// PA-014 : ClearAllTemporaryData
// =============================================================================

/**
 * @brief   Clears all RAM buffers including regular, event, image, and
 *          mid-transmission data.
 * @details Invoked by HandleShutdown upon IG-OFF event detection. Executes a
 *          sequential, mutex-protected clearing of all RAM buffers per the
 *          pseudocode specification:
 *
 *          clearSuccess = true.
 *          Step 1 — LOCK bufferMutex100ms_null; CLEAR canBuffer100ms_null;
 *                   UNLOCK; if clear failed: clearSuccess = false.
 *          Step 2 — LOCK bufferMutex1000ms_null; CLEAR canBuffer1000ms_null;
 *                   UNLOCK; if clear failed: clearSuccess = false.
 *          Step 3 — LOCK logBufferMutex_null; CLEAR logDataSetBuffer_null and
 *                   the internal LogDataSet deque; UNLOCK;
 *                   if clear failed: clearSuccess = false.
 *          Step 4 — CLEAR steadyStateDataBuffer100ms_null;
 *                   if clear failed: clearSuccess = false.
 *          Step 5 — CLEAR steadyStateDataBuffer1000ms_null;
 *                   if clear failed: clearSuccess = false.
 *          Step 6 — CLEAR eventSendingBuffer_null;
 *                   if clear failed: clearSuccess = false.
 *          Step 7 — CLEAR imageDataBuffer_null;
 *                   if clear failed: clearSuccess = false.
 *          Step 8 — If clearSuccess == false: CALL HandleRamDeletionFailure()
 *                   (RETURN_FAILURE_TO_CALLER). Else: return (RETURN_SUCCESS_TO_CALLER).
 *
 *          The function does not skip subsequent buffers on a single failure;
 *          it attempts to clear all remaining buffers to maximise purge
 *          completeness before signalling failure to the caller.
 *
 *          Thread-safety: each mutex is acquired and released individually in
 *          a consistent order (100ms → 1000ms → log) to prevent deadlock.
 * @pre     shutdownRequested_ == true or isRunning_ == false.
 * @post    All data buffers are empty.
 * @throws  None.
 * @note    Called by: ProbeApp::HandleShutdown().
 * @warning This operation is irreversible. All in-flight transmission data is lost.
 * @see     HandleShutdown, ClearSteadyStateBuffer
 * @requirements SWR-REQ-01-09-002;SWR-REQ-03-13-002
 */
void ProbeApp::ClearAllTemporaryData() noexcept
{
    bool clearSuccess{true};

    // Step 1: Clear CAN 100ms buffer under mutex
    {
        std::lock_guard<std::mutex> lock100ms{bufferMutex100ms_null};
        try {
            canBuffer100ms_null.clear();
        } catch (...) {
            clearSuccess = false;
        }
    }
    // RESULT_1 evaluated: clearSuccess updated above if FAIL

    // Step 2: Clear CAN 1000ms buffer under mutex
    {
        std::lock_guard<std::mutex> lock1000ms{bufferMutex1000ms_null};
        try {
            canBuffer1000ms_null.clear();
        } catch (...) {
            clearSuccess = false;
        }
    }
    // RESULT_2 evaluated: clearSuccess updated above if FAIL

    // Step 3: Clear log data set buffer under mutex
    {
        std::lock_guard<std::mutex> lockLog{logBufferMutex_null};
        try {
            logDataSetBuffer_null.clear();
            // Also clear the module-local LogDataSet deque for this instance
            std::deque<LogDataSet>& logDataSetBuffer = GetInstanceLogDeque(this);
            logDataSetBuffer.clear();
        } catch (...) {
            clearSuccess = false;
        }
    }
    // RESULT_3 evaluated: clearSuccess updated above if FAIL

    // Step 4: Clear steady-state 100ms buffer
    try {
        steadyStateDataBuffer100ms_null.clear();
    } catch (...) {
        clearSuccess = false;
    }
    // RESULT_4 evaluated: clearSuccess updated above if FAIL

    // Step 5: Clear steady-state 1000ms buffer
    try {
        steadyStateDataBuffer1000ms_null.clear();
    } catch (...) {
        clearSuccess = false;
    }
    // RESULT_5 evaluated: clearSuccess updated above if FAIL

    // Step 6: Clear event sending buffer
    try {
        eventSendingBuffer_null.clear();
    } catch (...) {
        clearSuccess = false;
    }
    // RESULT_6 evaluated: clearSuccess updated above if FAIL

    // Step 7: Clear image data buffer
    try {
        imageDataBuffer_null.clear();
    } catch (...) {
        clearSuccess = false;
    }
    // RESULT_7 evaluated: clearSuccess updated above if FAIL

    // Step 8: Report result to calling context (HandleShutdown)
    if (!clearSuccess) {
        // Signal deletion failure to HandleShutdown for escalation
        // RETURN_FAILURE_TO_CALLER
        HandleRamDeletionFailure();
    }
    // else: All buffers cleared successfully — RETURN_SUCCESS_TO_CALLER
}

// =============================================================================
// PA-015 : CheckCollectionStartDelay
// =============================================================================

/**
 * @brief   Verifies that data collection can start after the 10-second delay
 *          from IG-ON.
 * @details Evaluates whether the elapsed time since IG-ON has reached the
 *          required threshold. Executes the following constant-time sequence
 *          per the pseudocode specification:
 *
 *          Step 1 — If collectionStarted_ == true: RETURN true (short-circuit;
 *                   gate already open; no re-evaluation of startupTimeSec_).
 *          Step 2 — If startupTimeSec_ >= kStartupDelaySeconds (10U):
 *                     Step 3 — Set collectionStarted_ = true; RETURN true.
 *                   Else:
 *                     Step 4 — RETURN false (delay not yet elapsed).
 *
 *          The function contains no loops and no external calls. Execution is
 *          O(1) and deterministic. If startupTimeSec_ overflows beyond 10, the
 *          comparison resolves to true (safe direction: collection permitted
 *          rather than withheld indefinitely).
 *
 *          Error handling: the function is a pure predicate; no error states
 *          are raised. The caller is responsible for monotonically incrementing
 *          startupTimeSec_.
 * @pre     HandleInitialize() has been called; startupTimeSec_ is being
 *          incremented by the lifecycle infrastructure.
 * @post    If true is returned, collectionStarted_ == true.
 * @return  bool indicating whether data collection may begin.
 * @retval  true   The 10-second startup delay has elapsed and collection may start,
 *                 or collection was already authorised in a prior call.
 * @retval  false  The startup delay has not yet elapsed.
 * @throws  None.
 * @note    Called by: ProbeApp::Run() during startup phase.
 * @rationale A mandatory 10-second delay after IG-ON ensures ECU subsystems and
 *            SOME/IP services are fully initialised before data collection begins,
 *            preventing capture of transient startup artefacts.
 * @see     HandleInitialize, Run
 * @requirements SWR-REQ-01-10-003;SWR-REQ-03-01-001;SWR-REQ-03-16-003
 */
bool ProbeApp::CheckCollectionStartDelay() noexcept
{
    // Step 1: Short-circuit if collection has already been authorized
    if (collectionStarted_) {
        return true;
    }

    // Step 2: Check elapsed startup time against 10-second threshold
    if (startupTimeSec_ >= kStartupDelaySeconds) {
        // Step 3: Authorize collection and latch the flag
        collectionStarted_ = true;
        return true;
    } else {
        // Step 4: Delay not yet elapsed; withhold collection authorization
        return false;
    }
}

// =============================================================================
// PA-016 : EnforceStopOnRamCleanupFailure
// =============================================================================

/**
 * @brief   Halts application if RAM cleanup fails to prevent inconsistent state.
 * @details Performs a single deterministic action sequence per the pseudocode
 *          specification:
 *
 *          Step 1 — LOG_ERROR: write an error-level diagnostic message to
 *                   std::cerr for post-mortem diagnostics. The message records
 *                   the enforcement action. If the write itself fails, execution
 *                   continues to Step 2 (halt takes priority over diagnostics).
 *          Step 2 — Set isRunning_ = false via atomic store. The application's
 *                   cyclic Run loop evaluates this flag at each iteration
 *                   boundary; when false, the loop exits and no further cyclic
 *                   data collection or transmission is triggered.
 *          Step 3 — No further operations permitted. Execution Management
 *                   detects the stopped state and handles process lifecycle.
 *                   No buffer access, no service calls, no retry attempts.
 *
 *          The function is unconditional: once called, it always sets
 *          isRunning_ to false with no branching. It represents the terminal
 *          error handling path for RAM cleanup failure.
 *
 *          Nesting depth: 1. Cyclomatic complexity: 1. No dynamic allocation.
 *          No unbounded loops.
 * @pre     A RAM deletion failure has been detected by HandleRamDeletionFailure().
 * @post    isRunning_ == false.
 * @throws  None.
 * @note    Called by: ProbeApp::HandleRamDeletionFailure() exclusively.
 * @warning This is a safety-critical stop. Once called, the application must be
 *          restarted to resume normal operation. No recovery is possible.
 * @see     HandleRamDeletionFailure
 * @requirements SWR-REQ-01-08-003;SWR-REQ-03-13-003
 */
void ProbeApp::EnforceStopOnRamCleanupFailure() noexcept
{
    // Step 1: Log the enforcement action for post-mortem diagnostics
    // RAM cleanup has failed; the application must not continue in inconsistent state
    std::cerr << "[ERROR] ProbeApp::EnforceStopOnRamCleanupFailure: "
                 "RAM cleanup failure enforced: halting application execution\n";

    // Step 2: Set the runtime execution flag to false
    // This flag is evaluated by the Run loop and all cyclic handlers
    isRunning_.store(false);

    // Step 3: No further operations permitted
    // Execution Management will detect the stopped state and handle process lifecycle
    // No buffer access, no service calls, no retry attempts
}

} // namespace probe

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/**
 * @brief   Transmits steady-state sampled data to DAQ via SOME/IP UDP fire-and-forget
 *          at 100 ms and 1000 ms cycles.
 * @details On each invocation (called at the Cyclic_100ms execution context), this
 *          function first evaluates the isDaqCommEstablished_ flag. If DAQ communication
 *          is not yet established, no transmission is performed and the function returns
 *          immediately. When communication is established, it increments an internal
 *          cycleCounter, then unconditionally invokes
 *          ProbeComm::SendContinualShortDataCyclic100ms() with the 100 ms staging buffer.
 *          Every tenth invocation (i.e., at the 1000 ms boundary, when cycleCounter
 *          reaches 10), it additionally invokes
 *          ProbeComm::SendContinualLongDataCyclic1000ms() with the 1000 ms staging buffer.
 *          Both transmissions use SOME/IP over UDP fire-and-forget semantics; no
 *          acknowledgement is expected and no retry is performed on transmission failure.
 *          After each transmission attempt, DeleteTransmittedSteadyStateData() is called
 *          to remove the transmitted data from RAM. If that deletion fails,
 *          HandleRamDeletionFailure() is invoked and the function returns immediately.
 *          ClearSteadyStateBuffer() is called after each successful deletion to reset
 *          the buffer to its initial state. The cycleCounter resets to zero after
 *          reaching ten.
 *
 *          Thread-safety: Single-threaded execution context (Cyclic_100ms task).
 *          No dynamic allocation. No unbounded loops. Nesting depth: 2.
 *          Cyclomatic complexity: within bounds.
 *
 * @pre     isDaqCommEstablished_ == true (guarded internally); isRunning_ == true.
 * @post    Steady-state data payloads have been submitted to ProbeComm for transmission;
 *          steadyStateDataBuffer100ms_null and/or steadyStateDataBuffer1000ms_null are
 *          cleared; cycleCounter_ is incremented (and reset to 0 at 1000 ms boundary).
 * @throws  None — function is noexcept.
 * @note    Called by: ProbeApp::Run() at 100 ms cycle points.
 *          Complies with ISO 26262 ASIL-B. No retry on UDP fire-and-forget failure.
 * @warning If HandleRamDeletionFailure() is invoked, isRunning_ will be set to false
 *          and no further cyclic activity will be performed.
 * @see     DeleteTransmittedSteadyStateData, ClearSteadyStateBuffer,
 *          HandleRamDeletionFailure, ProbeComm::SendContinualShortDataCyclic100ms,
 *          ProbeComm::SendContinualLongDataCyclic1000ms
 * @requirements SWR-REQ-01-005;SWR-REQ-01-06-001;SWR-REQ-01-06-002;
 *               SWR-REQ-01-08-001;SWR-REQ-01-08-002
 * @rationale Fire-and-forget UDP semantics are mandated by the DAQ interface
 *            specification; no retry is performed to avoid blocking the cyclic task.
 */
void ProbeApp::SendRegularData() noexcept
{
    // Step 1: Guard transmission on DAQ communication establishment.
    // No transmission permitted before SOME/IP session is confirmed.
    if (isDaqCommEstablished_.load() == false)
    {
        std::cout << "[DEBUG] DAQ communication not established; skipping transmission cycle\n";
        return;
    }

    // Step 2: Increment cyclic invocation counter (uint32_t).
    cycleCounter_ = cycleCounter_ + 1U;

    // Step 3: Transmit 100ms cycle steady-state data (every invocation).
    // Fire-and-forget; no retry on failure. transmitResult100ms is informational only.
    {
        std::vector<uint8_t> flat100ms;
        for (const auto& row : steadyStateDataBuffer100ms_null) {
            flat100ms.insert(flat100ms.end(), row.begin(), row.end());
        }
        std::lock_guard<std::mutex> lock100ms(bufferMutex100ms_null);
        probeComm_->SendContinualShortDataCyclic100ms(flat100ms);
    }

    // Step 4: Delete transmitted 100ms data from RAM regardless of transmit result.
    DeleteTransmittedSteadyStateData();

    // Step 4a: Check if deletion failed by evaluating isRunning_ (set false on failure).
    if (isRunning_.load() == false)
    {
        // RAM deletion failed; HandleRamDeletionFailure was already invoked inside
        // DeleteTransmittedSteadyStateData's caller path. Return immediately.
        HandleRamDeletionFailure();
        return;
    }

    // Step 5: Clear 100ms steady-state buffer.
    ClearSteadyStateBuffer();

    // Step 6: Check if 1000ms boundary has been reached.
    if (cycleCounter_ >= 10U)
    {
        // Step 7: Transmit 1000ms cycle steady-state data.
        // Fire-and-forget; no retry on failure. transmitResult1000ms is informational only.
        {
            std::vector<uint8_t> flat1000ms;
            for (const auto& row : steadyStateDataBuffer1000ms_null) {
                flat1000ms.insert(flat1000ms.end(), row.begin(), row.end());
            }
            std::lock_guard<std::mutex> lock1000ms(bufferMutex1000ms_null);
            probeComm_->SendContinualLongDataCyclic1000ms(flat1000ms);
        }

        // Step 8: Delete transmitted 1000ms data from RAM regardless of transmit result.
        DeleteTransmittedSteadyStateData();

        // Step 8a: Check if deletion failed.
        if (isRunning_.load() == false)
        {
            HandleRamDeletionFailure();
            return;
        }

        // Step 9: Clear 1000ms steady-state buffer.
        ClearSteadyStateBuffer();

        // Step 10: Reset cycle counter.
        cycleCounter_ = 0U;
    }
}

/**
 * @brief   Removes transmitted steady-state data from RAM buffers after successful
 *          or failed transmission.
 * @details This function is invoked from SendRegularData() on the On_Request execution
 *          context following each transmission attempt. It attempts to erase all elements
 *          from both the 100 ms and 1000 ms steady-state staging buffers if they contain
 *          data. For each buffer, if the erase operation fails (detected by the buffer
 *          not being empty after the clear call), an error is logged and the function
 *          returns immediately, signalling failure to the caller via the isRunning_ flag
 *          path. On successful erasure of a buffer, ClearSteadyStateBuffer() is called
 *          to reset the buffer to its initial clean state.
 *
 *          The function applies to both steady-state buffers independently. It does not
 *          make decisions about which buffer to clear; that decision is owned by
 *          SendRegularData(). This function is a pure data lifecycle operation and does
 *          not interact with any external service or component.
 *
 *          Nesting depth: 1. Cyclomatic complexity: 2. No dynamic allocation.
 *          No unbounded loops.
 *
 * @pre     SendRegularData() has been called in the current cycle.
 * @post    steadyStateDataBuffer100ms_null and steadyStateDataBuffer1000ms_null are
 *          empty if no failure occurred; ClearSteadyStateBuffer() has been called for
 *          each successfully erased buffer.
 * @throws  None — function is noexcept.
 * @note    Called by: ProbeApp::SendRegularData() after each transmission attempt.
 *          Complies with ISO 26262 ASIL-B. No external service dependencies.
 * @warning On erase failure, the caller (SendRegularData) must invoke
 *          HandleRamDeletionFailure() to initiate a controlled application stop.
 *          The failure is signalled by the isRunning_ flag being set to false via
 *          the HandleRamDeletionFailure → EnforceStopOnRamCleanupFailure path.
 * @see     SendRegularData, HandleRamDeletionFailure, ClearSteadyStateBuffer
 * @requirements SWR-REQ-01-006;SWR-REQ-01-07-001;SWR-REQ-01-08-002
 * @rationale Separating the deletion step from the transmission step maintains
 *            single-responsibility integrity and allows independent failure escalation
 *            for each buffer lifecycle operation.
 */
void ProbeApp::DeleteTransmittedSteadyStateData() noexcept
{
    // Step 2: Erase 100ms buffer if it contains data.
    if (steadyStateDataBuffer100ms_null.size() > 0U)
    {
        steadyStateDataBuffer100ms_null.clear();

        // Verify the erase succeeded (std::vector::clear() is non-throwing but
        // we validate the post-condition to detect any unexpected residual state).
        if (steadyStateDataBuffer100ms_null.empty() == false)
        {
            // Step 2a: Signal deletion failure to caller.
            // Caller (SendRegularData) will invoke HandleRamDeletionFailure.
            std::cerr << "[ERROR] Failed to erase steadyStateDataBuffer100ms\n";
            return;
        }

        // Step 2b: Reset buffer to clean state.
        ClearSteadyStateBuffer();
    }

    // Step 3: Erase 1000ms buffer if it contains data.
    if (steadyStateDataBuffer1000ms_null.size() > 0U)
    {
        steadyStateDataBuffer1000ms_null.clear();

        // Verify the erase succeeded.
        if (steadyStateDataBuffer1000ms_null.empty() == false)
        {
            // Step 3a: Signal deletion failure to caller.
            std::cerr << "[ERROR] Failed to erase steadyStateDataBuffer1000ms\n";
            return;
        }

        // Step 3b: Reset buffer to clean state.
        ClearSteadyStateBuffer();
    }

    // Step 4: All deletions successful — return normally.
}

/**
 * @brief   Initiates a controlled application stop when a RAM buffer deletion failure
 *          is detected after a communication error.
 * @details This function is invoked from SendRegularData() on the Event_Trigger
 *          execution context whenever DeleteTransmittedSteadyStateData() signals a
 *          failure condition. It first evaluates the isRunning_ flag. If the application
 *          is already in the process of stopping (isRunning_ is false), the function
 *          returns immediately to avoid redundant state transitions. If the application
 *          is still running, the function logs the failure condition and then delegates
 *          unconditionally to EnforceStopOnRamCleanupFailure() to set isRunning_ to
 *          false and initiate the controlled shutdown sequence.
 *
 *          Design rationale: HandleRamDeletionFailure is a pure escalation router with
 *          no side effects beyond delegating to EnforceStopOnRamCleanupFailure. The
 *          logical separation between HandleRamDeletionFailure (context-aware escalation
 *          decision) and EnforceStopOnRamCleanupFailure (unconditional flag setter)
 *          maintains single-responsibility integrity for each function.
 *
 *          Nesting depth: 1. Cyclomatic complexity: 2. No dynamic allocation.
 *          No unbounded loops.
 *
 * @pre     A buffer deletion operation has failed; this function is called from
 *          SendRegularData() upon detecting the failure condition.
 * @post    If isRunning_ was true on entry: EnforceStopOnRamCleanupFailure() has been
 *          invoked; isRunning_ == false.
 *          If isRunning_ was already false on entry: no state change occurs.
 * @throws  None — function is noexcept.
 * @note    Called by: ProbeApp::SendRegularData() on buffer deletion failure.
 *          This is a safety-critical path per ISO 26262 ASIL-B.
 *          The isRunning_ flag assignment within EnforceStopOnRamCleanupFailure is
 *          unconditional and independent of any logging operation, ensuring resilience
 *          to diagnostic output failures.
 * @warning This is a safety-critical stop path. Once EnforceStopOnRamCleanupFailure()
 *          is called, the application will cease all cyclic data collection and
 *          transmission. A restart is required to resume normal operation.
 * @see     EnforceStopOnRamCleanupFailure, DeleteTransmittedSteadyStateData,
 *          SendRegularData
 * @requirements SWR-REQ-01-08-003
 * @rationale Separating the escalation decision (this function) from the unconditional
 *            halt enforcement (EnforceStopOnRamCleanupFailure) ensures that each
 *            function has a single, well-defined responsibility, simplifying verification
 *            and review under ISO 26262 ASIL-B.
 */
void ProbeApp::HandleRamDeletionFailure() noexcept
{
    // Step 1: Check if application is already stopping.
    // Avoid redundant halt escalation if isRunning_ is already false.
    if (isRunning_.load() == false)
    {
        // Application already halting; no action required.
        std::cout << "[DEBUG] HandleRamDeletionFailure called but application already stopping\n";
        return;
    }

    // Step 2: Application is still running; log the RAM deletion failure condition.
    std::cerr << "[ERROR] RAM buffer deletion failure detected; initiating controlled application stop\n";

    // Step 3: Escalate to enforcement function.
    // EnforceStopOnRamCleanupFailure will set isRunning_ = false.
    // This prevents any further cyclic data collection or transmission.
    EnforceStopOnRamCleanupFailure();

    // Step 4: Return to caller.
    // Run loop will evaluate isRunning_ == false on next iteration and exit.
}

} // namespace probe