/**
 * @file   ProbeCommVariant.cpp
 * @brief  Implementation of ProbeCommVariant component.
 * @details Portable C++ implementation generated by
 *          the Code Generation Pipeline.
 *          Uses runtime::IRuntime for all platform-dependent behavior.
 * @author  Engineering Team
 * @version 1.0.0
 * @copyright Copyright (c) 2024 Company. All rights reserved.
 */

#include "../ProbeCommVariant/ProbeCommVariant.hpp"
#include "ProbeCommVariant/ProbeCommVariant.hpp"
#include <algorithm>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

/**
 * @ingroup ProbeCommVariantModule
 */

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/**
 * @brief Constructs the variant configuration manager with default values.
 * @details Initializes all member variables to their default safe states.
 *          All feature flags are initialized to false (disabled). The variant code
 *          is set to the default variant code. This constructor does not perform
 *          any shared memory access or dictionary lookup. All std::string members
 *          are initialized to known safe values. Boolean flags default to false
 *          to ensure a safe-off state until explicitly configured.
 * @throws None — This constructor is noexcept.
 * @pre None.
 * @post All feature flags are false. variantCode_null equals defaultVariantCode_.
 *       variantReadSuccess_ is false.
 * @note Called by ProbeApp during component initialization.
 * @warning Must be followed by ReadVariantCode() and SetVariant() before querying features.
 * @see ReadVariantCode, SetVariant
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 * @rationale Initializes ProbeCommVariant with safe defaults to ensure deterministic
 *            behavior even if subsequent initialization steps fail.
 */
ProbeCommVariant::ProbeCommVariant() noexcept
    : variantCode_null{defaultVariantCode_},
      defaultVariantCode_{"00000"},
      regularProbeEnabled_{false},
      eventProbeEnabled_{false},
      eventProbeWithoutPictureEnabled_{false},
      gedrEnabled_{false},
      gedrWithoutPictureEnabled_{false},
      daqTransmissionEnabled_{false},
      variantDictionaryPath_nullnull,
      variantReadSuccess_{false}
{
    /* All members initialized via member initializer list.
     * No external service calls or I/O operations are performed.
     * Safe-off state: all feature flags are false. */
}

/**
 * @brief Cleans up variant configuration manager resources.
 * @details Releases all internal resources in a deterministic and bounded manner.
 *          All std::string members (variantCode_null, defaultVariantCode_,
 *          variantDictionaryPath_null) are automatically released by RAII semantics.
 *          All boolean flags (regularProbeEnabled_, eventProbeEnabled_,
 *          eventProbeWithoutPictureEnabled_, gedrEnabled_, gedrWithoutPictureEnabled_,
 *          daqTransmissionEnabled_, variantReadSuccess_) are primitive types requiring
 *          no explicit release. No external service interaction occurs during destruction.
 *          Destruction completes deterministically within bounded execution time.
 * @throws None — This destructor is noexcept.
 * @pre Object is in a valid state.
 * @post Object is destroyed and all resources are released.
 * @note Called by ProbeApp during component shutdown.
 * @see ProbeCommVariant
 */
ProbeCommVariant::~ProbeCommVariant() noexcept
{
    /* All std::string members are automatically released by RAII.
     * variantCode_null, defaultVariantCode_, variantDictionaryPath_null go out of scope.
     * All boolean flags are primitive types; no explicit release needed.
     * regularProbeEnabled_, eventProbeEnabled_, eventProbeWithoutPictureEnabled_,
     * gedrEnabled_, gedrWithoutPictureEnabled_, daqTransmissionEnabled_,
     * variantReadSuccess_ are released automatically.
     * No external service interaction during destruction.
     * Destruction completes deterministically. */
}

/**
 * @brief Reads the 5-byte variant code from shared memory during initialization.
 * @details Accesses shared memory via the SharedMem component to retrieve the
 *          variant code. If the read operation fails or the data is invalid,
 *          falls back to the default variant code. Sets the variantReadSuccess_
 *          flag to indicate whether the read was successful.
 *          After reading, invokes SetVariant() with the determined variant code
 *          to resolve feature flags from the variant dictionary.
 *          This method provides the SharedMemory_VariantCode interface.
 * @return The variant code string read from shared memory, or the default
 *         variant code if the read operation failed.
 * @retval non-empty string Successfully read variant code from shared memory
 *         or default variant code on fallback.
 * @throws None — Errors are handled internally with fallback to default.
 * @pre ProbeCommVariant object has been constructed.
 * @post variantCode_null is updated with the read value or default.
 *       variantReadSuccess_ reflects the outcome of the read operation.
 *       SetVariant() has been called with the determined variant code.
 * @note Called by ProbeApp at startup. This method should be called exactly once
 *       during the initialization sequence.
 * @warning Shared memory must be available and properly initialized before calling
 *          this method. If shared memory is unavailable, the default variant code
 *          is used silently.
 * @see SetVariant, SharedMem
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 * @rationale Reads variant code from shared memory to determine which probe
 *            features should be active for the current vehicle configuration.
 */
std::string ProbeCommVariant::ReadVariantCode()
{
    /* Attempt to read variant code from shared memory interface */
    const std::optional<std::string> readResult = SharedMem::Read("VariantCode");

    if (readResult.has_value() && (!readResult.value().empty()))
    {
        /* Assign the retrieved variant code */
        variantCode_null = readResult.value();
        variantReadSuccess_ = true;
    }
    else
    {
        /* Shared memory read failed; apply fallback */
        variantCode_null = defaultVariantCode_;
        variantReadSuccess_ = false;

        /* Log the read failure for diagnostics */
        std::cerr << "ReadVariantCode: shared memory read failed; applying default variant code"
                  << std::endl;
    }

    /* Invoke variant resolution with the determined code */
    SetVariant(variantCode_null);

    /* Return the active variant code to the caller */
    return variantCode_null;
}

/**
 * @brief Enables or disables collection features based on variant code matched against variant dictionary.
 * @details Loads the variant dictionary from the configured file path. If the dictionary
 *          cannot be loaded, logs an error and calls HandleMissingVariantCode() to disable
 *          all transmission. If loaded successfully, searches for the provided variant code
 *          in the dictionary. If the code is not found, logs an error and calls
 *          HandleMissingVariantCode(). If found, sets each feature flag based on whether
 *          the corresponding dictionary value equals "A" (active). Sets daqTransmissionEnabled_
 *          to true when the variant code is successfully resolved.
 *          Executes deterministically within bounded iteration over at most five feature keys.
 * @param[in] code The variant code string to look up in the variant dictionary.
 *                  Expected length: 5 characters. Valid range: any non-empty string
 *                  that may exist in the variant dictionary.
 * @throws None — Errors are handled internally via HandleMissingVariantCode().
 * @pre ReadVariantCode() has been called and returned a valid code.
 *      The variant dictionary is available at variantDictionaryPath_null.
 * @post All feature flags are updated according to the dictionary entry for the
 *       given code, or all flags are set to false if the code is not found.
 * @note Called by ProbeApp at startup after ReadVariantCode().
 * @warning If the variant code is not found in the dictionary, all data transmission
 *          will be disabled as a safety measure per SWR-REQ-01-03-003.
 * @see ReadVariantCode, HandleMissingVariantCode, DisableAllTransmissionOnInvalidVariant
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Sets variant and applies feature flags to control which probe data
 *            collection and transmission features are active for the current variant.
 */
void ProbeCommVariant::SetVariant(const std::string& code)
{
    /* Load the variant dictionary from configured path */
    std::ifstream dictionaryFile(variantDictionaryPath_null);
    const bool dictionaryLoadSuccess = dictionaryFile.is_open() && dictionaryFile.good();

    if (!dictionaryLoadSuccess)
    {
        /* Dictionary file missing or parse error */
        std::cerr << "SetVariant: variant dictionary load failed at path: "
                  << variantDictionaryPath_null << std::endl;
        HandleMissingVariantCode();
        return;
    }

    /* Parse the variant dictionary file.
     * Expected format per line: <variantCode>,<regularProbe>,<eventProbe>,
     *   <eventProbeWithoutPicture>,<gedr>,<gedrWithoutPicture>
     * Each feature value is "A" for active or any other value for inactive. */
    bool entryFound = false;
    std::string regularProbeValuenull;
    std::string eventProbeValuenull;
    std::string eventProbeWithoutPictureValuenull;
    std::string gedrValuenull;
    std::string gedrWithoutPictureValuenull;

    std::string linenull;
    while (std::getline(dictionaryFile, line))
    {
        /* Skip empty lines and comment lines */
        if (line.empty() || (line.at(0) == '#'))
        {
            continue;
        }

        std::istringstream lineStream(line);
        std::string entryCodenull;
        std::string fieldnull;

        /* Parse comma-separated fields */
        if (!std::getline(lineStream, entryCode, ','))
        {
            continue;
        }

        /* Trim whitespace from entry code for robust matching */
        const auto trimWhitespace = [](const std::string& str) -> std::string
        {
            const auto start = str.find_first_not_of(" \t\r
");
            if (start == std::string::npos)
            {
                return std::stringnull;
            }
            const auto end = str.find_last_not_of(" \t\r
");
            return str.substr(start, (end - start) + 1U);
        };

        const std::string trimmedEntryCode = trimWhitespace(entryCode);

        if (trimmedEntryCode == code)
        {
            entryFound = true;

            /* Read feature flag values from dictionary entry */
            if (std::getline(lineStream, field, ','))
            {
                regularProbeValue = trimWhitespace(field);
            }
            if (std::getline(lineStream, field, ','))
            {
                eventProbeValue = trimWhitespace(field);
            }
            if (std::getline(lineStream, field, ','))
            {
                eventProbeWithoutPictureValue = trimWhitespace(field);
            }
            if (std::getline(lineStream, field, ','))
            {
                gedrValue = trimWhitespace(field);
            }
            if (std::getline(lineStream, field, ','))
            {
                gedrWithoutPictureValue = trimWhitespace(field);
            }

            break;
        }
    }

    dictionaryFile.close();

    /* Search for the variant code entry in the dictionary */
    if (!entryFound)
    {
        /* Variant code not present in dictionary */
        std::cerr << "SetVariant: variant code not found in dictionary: "
                  << code << std::endl;
        HandleMissingVariantCode();
        return;
    }

    /* Apply feature flags based on dictionary entry values.
     * Activation value is "A"; all others mean disabled. */
    regularProbeEnabled_ = (regularProbeValue == "A");

    eventProbeEnabled_ = (eventProbeValue == "A");

    eventProbeWithoutPictureEnabled_ = (eventProbeWithoutPictureValue == "A");

    gedrEnabled_ = (gedrValue == "A");

    gedrWithoutPictureEnabled_ = (gedrWithoutPictureValue == "A");

    /* Enable DAQ transmission since variant code was resolved */
    daqTransmissionEnabled_ = true;

    /* Log all applied flag states for diagnostics */
    std::cout << "SetVariant: flags applied for code: " << code
              << " [regularProbe=" << (regularProbeEnabled_ ? "true" : "false")
              << ", eventProbe=" << (eventProbeEnabled_ ? "true" : "false")
              << ", eventProbeWithoutPicture=" << (eventProbeWithoutPictureEnabled_ ? "true" : "false")
              << ", gedr=" << (gedrEnabled_ ? "true" : "false")
              << ", gedrWithoutPicture=" << (gedrWithoutPictureEnabled_ ? "true" : "false")
              << ", daqTransmission=" << (daqTransmissionEnabled_ ? "true" : "false")
              << "]" << std::endl;
}

/**
 * @brief Returns whether regular probe data collection is enabled based on variant.
 * @details Checks the regularProbeEnabled_ flag which was set during SetVariant().
 *          This is a simple accessor with no side effects. Execution is bounded
 *          and deterministic in O(1). The caller uses the returned boolean to gate
 *          regular probe signal sampling and transmission.
 * @return True if regular probe data collection is enabled, false otherwise.
 * @retval true  Regular probe data collection is enabled for the current variant.
 * @retval false Regular probe data collection is disabled, or variant has not been set.
 * @throws None — This function is noexcept.
 * @pre SetVariant() has been called with a valid variant code.
 * @post No state change. This is a const query method.
 * @note Called by ProbeApp on request to determine if regular probe data should be collected.
 * @see SetVariant, CheckEventProbeEnabled
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Checks if regular probe is enabled to allow ProbeApp to conditionally
 *            activate regular probe data collection.
 */
bool ProbeCommVariant::CheckRegularProbeEnabled() const noexcept
{
    /* Return the current state of the regular probe feature flag */
    return regularProbeEnabled_;
}

/**
 * @brief Returns whether event probe data collection is enabled based on variant.
 * @details Checks the eventProbeEnabled_ flag which was set during SetVariant().
 *          This is a simple accessor with no side effects. Execution is bounded
 *          and deterministic in O(1). The caller uses the returned value to gate
 *          event probe processing.
 * @return True if event probe data collection is enabled, false otherwise.
 * @retval true  Event probe data collection is enabled for the current variant.
 * @retval false Event probe data collection is disabled, or variant has not been set.
 * @throws None — This function is noexcept.
 * @pre SetVariant() has been called with a valid variant code.
 * @post No state change. This is a const query method.
 * @note Called by ProbeApp on request to determine if event probe data should be collected.
 * @see SetVariant, CheckRegularProbeEnabled, CheckEventProbeWithoutPictureEnabled
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Checks if event probe is enabled to allow ProbeApp to conditionally
 *            activate event probe data collection.
 */
bool ProbeCommVariant::CheckEventProbeEnabled() const noexcept
{
    /* Return the current state of the event probe feature flag */
    return eventProbeEnabled_;
}

/**
 * @brief Returns whether event probe without picture is enabled based on variant.
 * @details Checks the eventProbeWithoutPictureEnabled_ flag which was set during
 *          SetVariant(). This is a simple accessor with no side effects. Execution
 *          is deterministic and bounded in O(1).
 * @return True if event probe without picture is enabled, false otherwise.
 * @retval true  Event probe without picture is enabled for the current variant.
 * @retval false Event probe without picture is disabled, or variant has not been set.
 * @throws None — This function is noexcept.
 * @pre SetVariant() has been called with a valid variant code.
 * @post No state change. This is a const query method.
 * @note Called by ProbeApp on request.
 * @see SetVariant, CheckEventProbeEnabled
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Checks if event probe without picture is enabled to allow ProbeApp
 *            to conditionally activate this specific collection mode.
 */
bool ProbeCommVariant::CheckEventProbeWithoutPictureEnabled() const noexcept
{
    /* Return the current state of the event probe without picture feature flag */
    return eventProbeWithoutPictureEnabled_;
}

/**
 * @brief Returns whether GEDR data collection is enabled based on variant.
 * @details Checks the gedrEnabled_ flag which was set during SetVariant().
 *          This is a simple accessor with no side effects. Execution is deterministic
 *          and bounded in O(1).
 * @return True if GEDR data collection is enabled, false otherwise.
 * @retval true  GEDR data collection is enabled for the current variant.
 * @retval false GEDR data collection is disabled, or variant has not been set.
 * @throws None — This function is noexcept.
 * @pre SetVariant() has been called with a valid variant code.
 * @post No state change. This is a const query method.
 * @note Called by ProbeApp on request to determine if GEDR data should be collected.
 * @see SetVariant, CheckGedrWithoutPictureEnabled
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Checks if GEDR is enabled to allow ProbeApp to conditionally
 *            activate GEDR data collection.
 */
bool ProbeCommVariant::CheckGedrEnabled() const noexcept
{
    /* Return the current state of the GEDR feature flag */
    return gedrEnabled_;
}

} // namespace probe

/**
 * @ingroup ProbeCommVariantModule
 */

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/**
 * @brief Returns whether GEDR without picture is enabled based on variant.
 * @details Reads the gedrWithoutPictureEnabled_ member flag and returns its current value
 *          without modifying any state. This is a pure accessor function with O(1) time
 *          complexity and deterministic execution. The returned value reflects the state
 *          set by the most recent call to SetVariant() or DisableAllTransmissionOnInvalidVariant().
 *          Thread-safety: Safe to call from a single thread context as designed.
 * @return True if GEDR without picture is enabled, false otherwise.
 * @retval true  GEDR without picture data collection is enabled for the current variant.
 * @retval false GEDR without picture data collection is disabled, or variant has not been set.
 * @throws None — This function is noexcept.
 * @pre SetVariant() has been called with a valid variant code.
 * @post No state change. This is a const query method.
 * @note Called by: ProbeApp on request to determine if GEDR without picture data should be collected.
 * @warning Returns false by default if variant has not been configured.
 * @see SetVariant, CheckGedrEnabled, DisableAllTransmissionOnInvalidVariant
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Provides a safe, const accessor for the GEDR without picture feature flag
 *            to allow ProbeApp to conditionally activate this specific collection mode.
 */
bool ProbeCommVariant::CheckGedrWithoutPictureEnabled() const noexcept
{
    /* Return the current state of the GEDR without picture feature flag */
    return gedrWithoutPictureEnabled_;
}

/**
 * @brief Returns whether DAQ transmission is enabled; disabled when variant code not found.
 * @details Reads the daqTransmissionEnabled_ member flag and returns its current value
 *          without modifying any state. This is a pure accessor function with O(1) time
 *          complexity and deterministic execution. When this flag is false, the calling
 *          context must suppress all outbound messages to DAQ to prevent transmission
 *          to an unconfigured destination. The flag is explicitly set to false when the
 *          variant code is not found in the dictionary, preventing any data transmission.
 *          Thread-safety: Safe to call from a single thread context as designed.
 * @return True if DAQ transmission is enabled, false otherwise.
 * @retval true  DAQ transmission is enabled for the current variant.
 * @retval false DAQ transmission is disabled, variant not found, or variant has not been set.
 * @throws None — This function is noexcept.
 * @pre SetVariant() has been called with a valid variant code.
 * @post No state change. This is a const query method.
 * @note Called by: ProbeApp on request to determine if data should be transmitted to DAQ.
 * @warning Returns false by default if variant code was not found in dictionary,
 *          ensuring no data is transmitted for unknown variants. Caller must suppress
 *          all DAQ transmission when this returns false.
 * @see SetVariant, HandleMissingVariantCode, DisableAllTransmissionOnInvalidVariant
 * @requirements SWR-REQ-01-03-002;SWR-REQ-01-03-003;SWR-REQ-03-14-002
 * @rationale Provides a safe, const accessor for the DAQ transmission enable flag
 *            to prevent data transmission when the variant is unknown or invalid.
 */
bool ProbeCommVariant::CheckDaqTransmissionEnabled() const noexcept
{
    /* Return the current state of the DAQ transmission enable flag */
    return daqTransmissionEnabled_;
}

/**
 * @brief Logs error and prevents data transmission when variant code not found in dictionary.
 * @details Called internally by SetVariant() when the provided variant code does not
 *          match any entry in the variant dictionary. Logs an error message to std::cerr
 *          containing the current variantCode_ and variantReadSuccess_ state for diagnostic
 *          context, then invokes DisableAllTransmissionOnInvalidVariant() to set all feature
 *          flags to false. After this call, no data collection or transmission to DAQ or
 *          GEDR is possible until a system restart provides a valid variant. Execution is
 *          deterministic and bounded in O(1).
 *          Thread-safety: Safe to call from a single thread context as designed.
 * @throws None — Errors are handled internally.
 * @pre SetVariant() has been called with a code not present in the variant dictionary.
 * @post All feature flags are set to false. An error message has been logged to std::cerr.
 * @note Called by: ProbeCommVariant (SetVariant) during startup when variant code is missing.
 * @warning This method disables ALL transmission features. Recovery requires a system
 *          restart with a valid variant code. No automatic recovery is provided.
 * @see SetVariant, DisableAllTransmissionOnInvalidVariant
 * @requirements SWR-REQ-01-03-003;SWR-REQ-03-14-003
 * @rationale Handles missing variant code as a safety measure to prevent data
 *            transmission with an unrecognized vehicle configuration, compliant
 *            with ISO 26262 ASIL-B requirements.
 */
void ProbeCommVariant::HandleMissingVariantCode()
{
    /* Log the error with variant code context */
    std::cerr << "HandleMissingVariantCode: variant code not resolved: "
              << variantCode_
              << " readSuccess: "
              << (variantReadSuccess_ ? "true" : "false")
              << std::endl;

    /* Disable all data transmission to DAQ and GEDR */
    DisableAllTransmissionOnInvalidVariant();

    /* No further processing; function returns */
}

/**
 * @brief Disables all data sending to DAQ and GEDR when variant is invalid.
 * @details Unconditionally sets all six feature enablement flags (regularProbeEnabled_,
 *          eventProbeEnabled_, eventProbeWithoutPictureEnabled_, gedrEnabled_,
 *          gedrWithoutPictureEnabled_, daqTransmissionEnabled_) to false in a sequential
 *          manner. There are no conditions or branches. No external service is accessed.
 *          After this function returns, all check functions (CheckRegularProbeEnabled,
 *          CheckEventProbeEnabled, CheckEventProbeWithoutPictureEnabled, CheckGedrEnabled,
 *          CheckGedrWithoutPictureEnabled, CheckDaqTransmissionEnabled) will return false,
 *          preventing any data flow. Logs the disablement for diagnostic traceability.
 *          Execution is deterministic and bounded in O(1).
 *          Thread-safety: Safe to call from a single thread context as designed.
 * @throws None — This function is noexcept.
 * @pre Called from HandleMissingVariantCode() or SetVariant() when variant is invalid.
 * @post All six feature flags are set to false. A diagnostic log message has been output.
 * @note Called by: ProbeCommVariant internally during startup error handling.
 * @warning After this call, no probe data collection or transmission will occur
 *          until SetVariant() is called again with a valid variant code.
 * @see HandleMissingVariantCode, SetVariant
 * @requirements SWR-REQ-01-03-003;SWR-REQ-03-14-003
 * @rationale Disables all transmission on invalid variant as a safety measure
 *            compliant with ISO 26262 ASIL-B requirements, ensuring no data is
 *            transmitted for an unrecognized vehicle configuration.
 */
void ProbeCommVariant::DisableAllTransmissionOnInvalidVariant() noexcept
{
    /* Unconditionally disable all collection and transmission flags */
    regularProbeEnabled_ = false;
    eventProbeEnabled_ = false;
    eventProbeWithoutPictureEnabled_ = false;
    gedrEnabled_ = false;
    gedrWithoutPictureEnabled_ = false;
    daqTransmissionEnabled_ = false;

    /* Log the disablement for diagnostic traceability */
    std::cout << "DisableAllTransmissionOnInvalidVariant: all transmission flags disabled"
              << std::endl;
}

} // namespace probe