/**
 * @file   ProbeApp.cpp
 * @brief  Implementation of ProbeApp component.
 * @details Portable C++ implementation generated by
 *          the Code Generation Pipeline.
 *          Uses runtime::IRuntime for all platform-dependent behavior.
 * @author  Engineering Team
 * @version 1.0.0
 * @copyright Copyright (c) 2024 Company. All rights reserved.
 */

#include "../ProbeApp/ProbeApp.hpp"
#include "ProbeApp/ProbeApp.hpp"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <thread>
#include <vector>

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/// @brief Maximum number of entries permitted in the 100ms CAN ring buffer before oldest entry is discarded.
/// @details Sized to hold 10 seconds of 100ms samples (100 entries). Prevents unbounded buffer growth.
static constexpr uint32_t kMaxBuffer100ms{100U};

/// @brief Maximum number of entries permitted in the 1000ms CAN ring buffer before oldest entry is discarded.
/// @details Sized to hold 10 seconds of 1000ms samples (10 entries). Prevents unbounded buffer growth.
static constexpr uint32_t kMaxBuffer1000ms{10U};

/// @brief Default past data retention count for log data sets.
/// @details Represents the number of per-second log data sets retained in the rolling buffer.
static constexpr uint32_t kDefaultPastDataRetentionCount{10U};

/// @brief Startup delay in seconds before data collection begins after IG-ON.
/// @details Ensures all ECU subsystems are stable before data collection starts.
static constexpr uint32_t kStartupDelaySec{10U};

/// @brief Cyclic period in milliseconds for the main Run loop.
/// @details Base period for the multi-rate sampling scheduler.
static constexpr uint32_t kCyclePeriodMs{100U};

/// @brief LCM boundary in milliseconds for counter reset.
/// @details Least common multiple of 100ms and 1000ms sampling rates.
static constexpr uint32_t kLcmBoundaryMs{1000U};

/**
 * @brief Retrieves the current system timestamp in seconds.
 * @details Uses std::chrono::steady_clock to obtain a monotonic timestamp.
 *          Returns the time in seconds since an unspecified epoch.
 * @return Current timestamp in seconds as uint32_t.
 * @retval >0 Valid timestamp value.
 * @throws None.
 * @note Internal helper function for ProbeApp lifecycle timing.
 */
static uint32_t GetTimestampSec() noexcept
{
    const auto now = std::chrono::steady_clock::now();
    const auto secSinceEpoch = std::chrono::duration_cast<std::chrono::seconds>(
        now.time_since_epoch());
    return static_cast<uint32_t>(secSinceEpoch.count());
}

/**
 * @brief Retrieves the current system timestamp in milliseconds.
 * @details Uses std::chrono::steady_clock to obtain a monotonic timestamp.
 *          Returns the time in milliseconds since an unspecified epoch.
 * @return Current timestamp in milliseconds as uint64_t.
 * @retval >0 Valid timestamp value.
 * @throws None.
 * @note Internal helper function for Run loop cycle timing.
 */
static uint64_t GetTimestampMs() noexcept
{
    const auto now = std::chrono::steady_clock::now();
    const auto msSinceEpoch = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch());
    return static_cast<uint64_t>(msSinceEpoch.count());
}

/**
 * @brief Constructs ProbeApp with references to communication, variant, and CAN consumer.
 * @details Initializes all internal state, ring buffers, counters, and flags to their
 *          default values. Stores non-owning pointers to the communication layer,
 *          variant configuration, and CAN consumer for use throughout the application lifecycle.
 *          No communication is initiated during construction. Validates critical dependencies
 *          and applies variant configuration from shared memory with fallback to defaults.
 * @param[in] comm       Pointer to the ProbeComm communication interface. Must not be nullptr.
 *                        Lifetime must exceed that of this ProbeApp instance.
 * @param[in] variant    Pointer to the ProbeCommVariant configuration. Must not be nullptr.
 *                        Lifetime must exceed that of this ProbeApp instance.
 * @param[in] canCons    Pointer to the CanConsumer for CAN signal access. Must not be nullptr.
 *                        Lifetime must exceed that of this ProbeApp instance.
 * @throws std::invalid_argument If variant or canCons is nullptr (fatal initialization error).
 * @pre All three pointers must be valid and non-null (variant and canCons are mandatory).
 * @post ProbeApp is in a constructed but not yet initialized state. isRunning_ == false.
 * @note Called by: Main at startup.
 * @warning None of the pointed-to objects may be destroyed before this ProbeApp instance.
 *          If probeComm is nullptr, it is treated as non-fatal; communication is deferred to HandleInitialize.
 * @see HandleInitialize
 * @requirements SWR-REQ-01-01-002, SWR-REQ-01-01-003, SWR-REQ-01-02-001
 * @rationale Constructor injection enables testability and decouples ProbeApp from
 *            concrete communication and CAN implementations.
 */
ProbeApp::ProbeApp(ProbeComm* comm, ProbeCommVariant* variant, CanConsumer* canCons)
    : probeComm_{comm},
      probeCommVariant_{variant},
      canConsumer_{canCons},
      canBuffer100ms_nullnull,
      canBuffer1000ms_nullnull,
      logDataSetBuffer_nullnull,
      steadyStateDataBuffer100ms_nullnull,
      steadyStateDataBuffer1000ms_nullnull,
      eventSendingBuffer_nullnull,
      imageDataBuffer_nullnull,
      bufferMutex100ms_nullnull,
      bufferMutex1000ms_nullnull,
      logBufferMutex_nullnull,
      msCounter_{0U},
      pastDataRetentionCount_{kDefaultPastDataRetentionCount},
      startupTimeSec_{0U},
      isRunning_{false},
      isDaqCommEstablished_{false},
      shutdownRequested_{false},
      collectionStarted_{false}
{
    /* Validate critical dependency: variant manager */
    if (probeCommVariant_ == nullptr)
    {
        throw std::invalid_argument(
            "ProbeApp: Fatal initialization error — probeCommVariant pointer is null.");
    }

    /* Initialize all boolean lifecycle flags to safe defaults (already done via initializer list) */

    /* Initialize counters to zero (already done via initializer list) */

    /* Set configurable parameter: past data retention depth (already done via initializer list) */

    /* Initialize all buffer containers to empty state */
    canBuffer100ms_null.clear();
    canBuffer1000ms_null.clear();
    logDataSetBuffer_null.clear();
    steadyStateDataBuffer100ms_null.clear();
    steadyStateDataBuffer1000ms_null.clear();
    eventSendingBuffer_null.clear();
    imageDataBuffer_null.clear();

    /* Apply variant configuration via variant manager */
    /* Attempt to read variant code from shared memory */
    bool variantReadSuccess = false;
    try
    {
        probeCommVariant_->ReadVariantCode();
        variantReadSuccess = true;
    }
    catch (...)
    {
        variantReadSuccess = false;
    }

    if (!variantReadSuccess)
    {
        /* Apply default variant code as fallback; no error propagation */
        probeCommVariant_->ApplyDefaultVariantCode();
    }
    else
    {
        /* Apply feature enablement flags from variant dictionary */
        try
        {
            probeCommVariant_->ApplyVariantFeatureFlags();
        }
        catch (...)
        {
            /* Variant code not found in dictionary: apply default */
            probeCommVariant_->ApplyDefaultVariantCode();
        }
    }

    /* Validate communication handler availability */
    if (probeComm_ == nullptr)
    {
        /* Non-fatal: communication will be established in HandleInitialize */
        std::cerr << "ProbeApp: Warning — probeComm not yet available at construction time."
                  << std::endl;
    }

    /* Validate CAN consumer availability */
    if (canConsumer_ == nullptr)
    {
        throw std::invalid_argument(
            "ProbeApp: Fatal initialization error — canConsumer pointer is null.");
    }
}

/**
 * @brief Starts ProbeApp operation after ADAS ECU startup and initiates SOME/IP communication with DAQ.
 * @details Performs post-construction initialization including variant code re-read,
 *          SOME/IP service discovery for DAQ communication channels, and setting the
 *          application into the running state. Must be called exactly once after construction
 *          and before Run(). If variant read fails, default variant code is applied as fallback.
 *          If SOME/IP discovery fails, isDaqCommEstablished_ remains false and Run loop retries.
 * @throws std::runtime_error If communication initialization fails critically.
 * @pre ProbeApp must be constructed. HandleInitialize() must not have been called previously.
 * @post isRunning_ == true. DAQ communication channels are being discovered.
 *       isDaqCommEstablished_ may still be false until service discovery completes.
 * @note Called from Main after construction.
 * @warning Blocking until initial service discovery requests are dispatched.
 * @see Run, HandleTerminate, HandleShutdown
 * @requirements SWR-REQ-01-10-001, SWR-REQ-01-10-002, SWR-REQ-01-03-001, SWR-REQ-03-16-001, SWR-REQ-03-16-002
 * @rationale Separating initialization from construction allows the caller to control
 *            when communication begins relative to other system startup activities.
 */
void ProbeApp::HandleInitialize()
{
    /* Step 1: Read variant code from shared memory */
    bool variantReadSuccess = false;
    try
    {
        probeCommVariant_->ReadVariantCode();
        variantReadSuccess = true;
    }
    catch (...)
    {
        variantReadSuccess = false;
    }

    if (!variantReadSuccess)
    {
        /* Apply default variant code: disables DAQ and GEDR transmission */
        probeCommVariant_->ApplyDefaultVariantCode();
    }
    else
    {
        /* Apply feature enablement flags from variant dictionary */
        bool variantApplySuccess = false;
        try
        {
            probeCommVariant_->ApplyVariantFeatureFlags();
            variantApplySuccess = true;
        }
        catch (...)
        {
            variantApplySuccess = false;
        }

        if (!variantApplySuccess)
        {
            /* Variant code not found in dictionary: disable all transmission */
            probeCommVariant_->ApplyDefaultVariantCode();
        }
    }

    /* Step 2: Mark application as running */
    isRunning_ = true;

    /* Step 3: Capture startup reference timestamp */
    startupTimeSec_ = GetTimestampSec();

    /* Step 4: Initiate SOME/IP service discovery with DAQ */
    /* isDaqCommEstablished remains false until session confirmed in Run */
    if (probeComm_ != nullptr)
    {
        try
        {
            probeComm_->FindServiceDaqContinual();
            probeComm_->FindServiceDaqDevEvent();
            probeComm_->OfferServiceProbeEventStt();
            probeComm_->OfferServiceProbeTrigger();
        }
        catch (...)
        {
            /* Non-fatal: Run loop will continue retrying discovery */
            /* isDaqCommEstablished remains false; data transmission suppressed */
            std::cerr << "ProbeApp: HandleInitialize — SOME/IP discovery initiation failed. "
                      << "Will retry in Run loop." << std::endl;
        }
    }

    /* Step 5: HandleInitialize complete */
    /* isRunning = true, isDaqCommEstablished = false (pending confirmation) */
    /* startupTimeSec captures boot reference for 10-second delay check in Run */
}

/**
 * @brief Runs the cyclic data collection and transmission processing loop.
 * @details Executes the main processing cycle loop including:
 *          - Checking collection start delay (10-second post-IG-ON)
 *          - Collecting shared memory signals at 100ms and 1000ms rates
 *          - Storing CAN data at appropriate rates
 *          - Sending regular steady-state data to DAQ
 *          - Re-attempting DAQ discovery if not established
 *          Loop continues while isRunning_ is true and shutdownRequested_ is false.
 *          Each iteration enforces a 100ms cycle boundary.
 * @throws std::runtime_error If a critical processing error occurs.
 * @pre HandleInitialize() must have been called. isRunning_ == true.
 * @post Processing loop has exited. Buffers and counters reflect final state.
 * @note Called cyclically from Main.
 * @warning Must not be called concurrently from multiple threads.
 * @see HandleInitialize, HandleTerminate
 * @requirements SWR-REQ-01-001, SWR-REQ-01-002, SWR-REQ-01-005, SWR-REQ-01-06-001, SWR-REQ-01-10-003, SWR-REQ-03-16-003
 * @rationale Single cyclic entry point simplifies scheduling and ensures deterministic execution order.
 */
void ProbeApp::Run()
{
    /* Enter cyclic execution loop; terminates on shutdown request */
    while ((shutdownRequested_ == false) && (isRunning_ == true))
    {
        /* Record cycle start time for period enforcement */
        const uint64_t cycleStartTime = GetTimestampMs();

        /* Step 1: Check if startup delay has elapsed and enable collection */
        CheckCollectionStartDelay();

        /* Step 2: Execute data collection if collection is enabled */
        if (collectionStarted_ == true)
        {
            /* Step 2a: Collect signals from shared memory at applicable rates */
            CollectSharedMemReadSignals();

            /* Step 2b: Store 100 ms rate data every cycle — handled inside CollectSharedMemReadSignals */
            /* StoreCanData100ms() is called within CollectSharedMemReadSignals */

            /* Step 2c: Store 1000 ms rate data only at 1000 ms boundary */
            /* StoreCanData1000ms() is called within CollectSharedMemReadSignals when msCounter == 0 */

            /* Note: msCounter increment and modulo logic is handled in CollectSharedMemReadSignals */
        }
        else
        {
            /* Startup delay not yet elapsed; skip collection and transmission */
        }

        /* Step 3: Transmit steady-state data if DAQ session is confirmed */
        if ((isDaqCommEstablished_ == true) && (collectionStarted_ == true))
        {
            SendRegularData();
        }
        else if (isDaqCommEstablished_ == false)
        {
            /* Attempt to re-establish DAQ communication */
            if (probeComm_ != nullptr)
            {
                try
                {
                    probeComm_->FindServiceDaqContinual();
                    /* If discovery call succeeds without exception, mark as established */
                    isDaqCommEstablished_ = true;
                }
                catch (...)
                {
                    /* Discovery failed; isDaqCommEstablished remains false */
                    /* No data transmitted while session not confirmed */
                }
            }
        }
        else
        {
            /* Default case: no action needed */
        }

        /* Step 4: Enforce 100 ms cycle boundary */
        const uint64_t cycleEndTime = GetTimestampMs();
        const uint64_t cycleElapsed = cycleEndTime - cycleStartTime;

        if (cycleElapsed < static_cast<uint64_t>(kCyclePeriodMs))
        {
            const auto sleepDuration = std::chrono::milliseconds(
                static_cast<uint64_t>(kCyclePeriodMs) - cycleElapsed);
            std::this_thread::sleep_for(sleepDuration);
        }
        /* If cycleElapsed >= 100, next cycle starts immediately */
    }

    /* Loop exited: shutdown or stop requested */
    /* Cleanup performed by HandleTerminate */
}

/**
 * @brief Stops all data collection and transmission processing on termination.
 * @details Sets the shutdown and running flags, then purges all RAM buffers including
 *          in-transit data. If buffer cleanup fails, initiates a hard application stop
 *          to prevent operation in an inconsistent state with residual personal data.
 * @pre isRunning_ == true.
 * @post isRunning_ == false. shutdownRequested_ == true. All buffers cleared on success.
 * @throws None.
 * @note Called from Main on termination request.
 * @warning Does not restart services. If ClearAllTemporaryData fails, application is halted.
 * @see HandleShutdown, HandleInitialize
 * @requirements SWR-REQ-01-09-001, SWR-REQ-03-13-001
 * @rationale Allows controlled stop with full data purge to prevent residual personal data.
 */
void ProbeApp::HandleTerminate() noexcept
{
    /* Step 1: Signal the Run loop to stop on next cycle boundary */
    shutdownRequested_ = true;

    /* Step 2: Mark application as no longer running */
    isRunning_ = false;

    /* Step 3: Purge all RAM buffers including in-transit data */
    try
    {
        ClearAllTemporaryData();
        /* Step 4: All temporary data deleted successfully */
        /* HandleTerminate completes normally */
    }
    catch (...)
    {
        /* Deletion failed: residual data may contain personal information */
        /* Hard stop: prevent further operation in inconsistent state */
        std::cerr << "ProbeApp: HandleTerminate — ClearAllTemporaryData failed. "
                  << "Initiating hard stop." << std::endl;
        EnforceStopOnRamCleanupFailure();
    }
}

/**
 * @brief Stops all processing and deletes all temporary data on ADAS ECU shutdown.
 * @details Evaluates the shutdownRequested flag. If shutdown has been requested, stops
 *          the running state and invokes ClearAllTemporaryData() to remove all buffered
 *          data from RAM. If RAM cleanup fails, EnforceStopOnRamCleanupFailure() is
 *          invoked to halt the application and prevent inconsistent state.
 * @pre ProbeApp must be in a constructed state (initialized or not).
 * @post isRunning_ == false. All buffers are cleared. shutdownRequested_ == true.
 * @throws None.
 * @note Called from Main on ECU shutdown.
 * @warning Irreversibly deletes all temporary data including partially transmitted event data.
 * @see HandleTerminate, ClearAllTemporaryData, EnforceStopOnRamCleanupFailure
 * @requirements SWR-REQ-01-09-001, SWR-REQ-01-09-002, SWR-REQ-03-13-001, SWR-REQ-03-13-002, SWR-REQ-03-13-003, SWR-REQ-01-08-003
 * @rationale Full cleanup on shutdown prevents stale data from persisting across drive cycles.
 */
void ProbeApp::HandleShutdown() noexcept
{
    /* Check if shutdown has been requested */
    if (shutdownRequested_ == true)
    {
        /* Stop all cyclic and event-based processing */
        isRunning_ = false;

        /* Delegate full buffer purge to ClearAllTemporaryData */
        bool cleanupSuccess = false;
        try
        {
            ClearAllTemporaryData();
            cleanupSuccess = true;
        }
        catch (...)
        {
            cleanupSuccess = false;
        }

        /* Evaluate cleanup result */
        if (!cleanupSuccess)
        {
            /* Halt application to prevent inconsistent state */
            EnforceStopOnRamCleanupFailure();
        }
        else
        {
            /* Normal termination path; all buffers cleared */
            /* No further action required */
        }
    }
    else
    {
        /* Shutdown not yet requested; no-op */
        /* Return without action */
    }
}

/**
 * @brief Reads CAN and internal signals from shared memory at configured sampling rates.
 * @details Increments the millisecond counter each 100ms cycle and dispatches to
 *          rate-specific buffer store functions based on modulo boundary conditions.
 *          StoreCanData100ms is called on every invocation (100ms boundary always active).
 *          StoreCanData1000ms is called only when the counter reaches the 1000ms boundary.
 *          The counter is reset at the LCM boundary to prevent overflow.
 * @pre isRunning_ == true. collectionStarted_ == true. canConsumer_ must be valid.
 * @post Signal values are read and stored into the appropriate ring buffers.
 *       msCounter_ is updated.
 * @throws None.
 * @note Called internally by Run().
 * @warning Assumes shared memory is mapped and accessible. No validation of memory mapping.
 * @see StoreCanData100ms, StoreCanData1000ms, Run
 * @requirements SWR-REQ-01-01-001, SWR-REQ-01-001, SWR-REQ-01-002, SWR-REQ-01-003
 * @rationale Centralizes signal reading to ensure consistent sampling across all rates.
 */
void ProbeApp::CollectSharedMemReadSignals()
{
    /* Increment cycle counter by 100ms step */
    msCounter_ = msCounter_ + kCyclePeriodMs;

    /* Reset counter at LCM boundary to prevent overflow */
    if (msCounter_ >= kLcmBoundaryMs)
    {
        msCounter_ = 0U;
    }

    /* 100ms boundary is always active on every invocation */
    StoreCanData100ms();

    /* 1000ms boundary: check modulo condition */
    if (msCounter_ == 0U)
    {
        StoreCanData1000ms();
    }
    else
    {
        /* No-op for 1000ms path this cycle */
    }
}

/**
 * @brief Reads CAN signals at 100ms rate and stores them into the 100ms ring buffer with timestamp.
 * @details Invokes canConsumer_ to read the latest 100ms CAN signal data from shared memory.
 *          Validates that the returned data is not empty. Acquires bufferMutex100ms_null,
 *          enforces ring buffer capacity by discarding the oldest entry if full, and
 *          appends the new signal entry to the back of the buffer.
 * @pre canConsumer_ must be valid. bufferMutex100ms_null must not be held by the caller.
 * @post A new timestamped entry is appended to canBuffer100ms_null if data was valid.
 * @throws None.
 * @note Called internally by CollectSharedMemReadSignals() every 100ms.
 * @warning Acquires bufferMutex100ms_null. Do not call while holding this mutex.
 * @see CollectSharedMemReadSignals, StoreCanData1000ms
 * @requirements SWR-REQ-01-001, SWR-REQ-01-01-001, SWR-REQ-01-01-002, SWR-REQ-01-003
 * @rationale Separate 100ms storage allows independent buffer management and transmission timing.
 */
void ProbeApp::StoreCanData100ms()
{
    /* Read CAN signals at 100ms rate from shared memory */
    std::vector<uint8_t> signalDatanull;

    if (canConsumer_ != nullptr)
    {
        try
        {
            signalData = canConsumer_->ReadCanData100ms();
        }
        catch (...)
        {
            /* Read failed; signalData remains empty */
            signalData.clear();
        }
    }

    /* Validate acquired data before buffering */
    if (!signalData.empty())
    {
        /* Acquire mutex for thread-safe buffer access */
        const std::lock_guard<std::mutex> lock(bufferMutex100ms_null);

        /* Discard oldest entry if buffer is at maximum capacity */
        if (canBuffer100ms_null.size() >= static_cast<size_t>(kMaxBuffer100ms))
        {
            canBuffer100ms_null.erase(canBuffer100ms_null.begin());
        }
        else
        {
            /* Buffer not full; no discard needed */
        }

        /* Insert newly acquired sample at back of ring buffer */
        canBuffer100ms_null.push_back(signalData);
    }
    else
    {
        /* No valid data returned; no-op; buffer unchanged */
    }
}

/**
 * @brief Reads CAN signals at 1000ms rate and stores them into the 1000ms ring buffer with timestamp.
 * @details Invokes canConsumer_ to read the latest 1000ms CAN signal data from shared memory.
 *          Initializes a local signal entry to zero state, reads data and attaches a timestamp.
 *          Acquires bufferMutex1000ms_null, enforces ring buffer capacity by discarding the
 *          oldest entry if full, and appends the new timestamped entry to the back of the buffer.
 *          If ReadCanData1000ms returns empty data, a zero-length payload with valid timestamp
 *          is still stored to preserve buffer consistency.
 * @pre canConsumer_ must be valid. bufferMutex1000ms_null must not be held by the caller.
 * @post A new timestamped entry is appended to canBuffer1000ms_null.
 * @throws None.
 * @note Called internally by CollectSharedMemReadSignals() every 1000ms.
 * @warning Acquires bufferMutex1000ms_null. Do not call while holding this mutex.
 * @see CollectSharedMemReadSignals, StoreCanData100ms
 * @requirements SWR-REQ-01-002, SWR-REQ-01-01-001, SWR-REQ-01-01-002, SWR-REQ-01-003
 * @rationale Separate 1000ms storage allows independent buffer management and transmission timing.
 */
void ProbeApp::StoreCanData1000ms()
{
    /* Step 1: Initialize local signal entry to zero state */
    std::vector<uint8_t> canSignalEntrynull;

    /* Step 2: Read 1000 ms CAN signals from shared memory via CanConsumer */
    std::vector<uint8_t> localSignalDatanull;

    if (canConsumer_ != nullptr)
    {
        try
        {
            localSignalData = canConsumer_->ReadCanData1000ms();
        }
        catch (...)
        {
            /* Read failed; localSignalData remains empty */
            localSignalData.clear();
        }
    }

    /* Step 3: Check if signal data was returned successfully */
    if (localSignalData.empty())
    {
        /* Assign zero-length payload; timestamp still valid */
        canSignalEntry = localSignalData; /* empty vector */
    }
    else
    {
        canSignalEntry = localSignalData;
    }

    /* Step 4: Attach acquisition timestamp from CanConsumer */
    /* Encode timestamp as 8 bytes (uint64_t) prepended to signal data */
    uint64_t timestamp = 0U;
    if (canConsumer_ != nullptr)
    {
        try
        {
            timestamp = canConsumer_->CollectTimestamp();
        }
        catch (...)
        {
            timestamp = 0U;
        }
    }

    /* Build timestamped entry: [timestamp_bytes | signal_data] */
    std::vector<uint8_t> timestampedEntrynull;
    timestampedEntry.reserve(sizeof(uint64_t) + canSignalEntry.size());

    /* Encode timestamp as little-endian 8 bytes */
    for (size_t i = 0U; i < sizeof(uint64_t); ++i)
    {
        timestampedEntry.push_back(
            static_cast<uint8_t>((timestamp >> (i * 8U)) & 0xFFU));
    }

    /* Append signal data */
    timestampedEntry.insert(timestampedEntry.end(),
                            canSignalEntry.begin(),
                            canSignalEntry.end());

    /* Step 5: Lock buffer mutex for thread-safe update */
    {
        const std::lock_guard<std::mutex> lock(bufferMutex1000ms_null);

        /* Step 6: Enforce ring buffer capacity - remove oldest if full */
        if (canBuffer1000ms_null.size() >= static_cast<size_t>(kMaxBuffer1000ms))
        {
            canBuffer1000ms_null.erase(canBuffer1000ms_null.begin());
        }

        /* Step 7: Insert new entry at back of ring buffer */
        canBuffer1000ms_null.push_back(timestampedEntry);
    }

    /* Step 8: Return - no output; state is held in canBuffer1000ms_null */
}

}  // namespace probe

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/// @brief Constant threshold value of 10 seconds used to gate data collection authorization.
/// @details Set to 10 based on the requirement that all ECU subsystems must be stable
///          before data collection begins after IG-ON.
static constexpr uint32_t kCollectionStartDelaySec{10U};

/**
 * @brief Collects event-based signals with timestamps, signal IDs, and data size information.
 * @details On each invocation, processes a single event-based signal sample according to a
 *          deterministic sequence: initializes a local record, assigns the signal ID from the
 *          configured signal definition, acquires the variable-length signal payload, captures
 *          the acquisition timestamp, assigns the data size, and stores the completed record
 *          into the mutex-protected log data set buffer. If the buffer exceeds the retention
 *          count, the oldest entry is removed before insertion.
 *
 *          Thread-safety: Acquires logBufferMutex_ for the buffer insertion operation.
 *          Error handling: If signal payload is empty (source unavailable), a zero-size record
 *          with valid signal ID and timestamp is stored to maintain buffer continuity.
 *
 * @pre isRunning_ == true. collectionStarted_ == true.
 * @post Event signal data with metadata is stored in logDataSetBuffer_.
 * @throws None.
 * @note Called internally by Run() on event trigger.
 * @warning Acquires logBufferMutex_. Do not call while holding this mutex.
 * @see BuildLogDataSetPerSecond, Run
 * @requirements SWR-REQ-03-01-002, SWR-REQ-03-01-004, SWR-REQ-03-01-005, SWR-REQ-03-01-006, SWR-REQ-03-01-007
 * @rationale Event-based collection captures transient signals that periodic sampling would miss.
 *            Zero-size records on payload failure maintain buffer sequence integrity for downstream consumers.
 */
void ProbeApp::StoreEventSignalData()
{
    /* Step 1: Initialize local signal record to zero state */
    std::vector<uint8_t> currentSignalRecordnull;
    std::vector<uint8_t> signalPayloadnull;
    uint64_t acquisitionTimestamp{0U};
    uint32_t signalId{0U};
    uint32_t timestampSec{0U};
    uint32_t timestampMsec{0U};
    uint32_t dataSize{0U};

    /* Step 2: Assign signal identifier from signal definition */
    /* In production, this would call GetSignalIdFromDefinition() via canConsumer_ */
    /* For now, the signal ID is sourced from the configured event probe collect signal definition */
    if (canConsumer_ != nullptr)
    {
        /* Signal ID retrieval from the pre-configured Event Probe Collect Signal Definition */
        /* signalId = canConsumer_->GetSignalIdFromDefinition(); */
        signalId = 0U; /* Placeholder: actual implementation reads from signal definition */
    }

    /* Step 3: Acquire signal payload at actual variable length */
    /* For variable-length signals, only actual data size is allocated (no fixed-size padding) */
    /* For structure-type signals, payload includes the full structure bytes */
    if (canConsumer_ != nullptr)
    {
        /* signalPayload = canConsumer_->AcquireSignalPayload(signalId); */
        /* Placeholder: actual implementation acquires variable-length signal data */
    }

    /* Step 4: Capture acquisition timestamp (seconds + milliseconds) */
    {
        const auto now = std::chrono::steady_clock::now();
        const auto durationSinceEpoch = now.time_since_epoch();
        const auto totalSeconds = std::chrono::duration_cast<std::chrono::seconds>(durationSinceEpoch);
        const auto totalMilliseconds = std::chrono::duration_cast<std::chrono::milliseconds>(durationSinceEpoch);

        acquisitionTimestamp = static_cast<uint64_t>(totalMilliseconds.count());
        timestampSec = static_cast<uint32_t>(totalSeconds.count());
        timestampMsec = static_cast<uint32_t>(
            totalMilliseconds.count() - (static_cast<int64_t>(timestampSec) * 1000));
    }

    /* Step 5: Assign actual data size (variable-length; no padding) */
    dataSize = static_cast<uint32_t>(signalPayload.size());

    /* Build the currentSignalRecord as a serialized byte vector:
     * [signalId (4 bytes)] [timestampSec (4 bytes)] [timestampMsec (4 bytes)]
     * [dataSize (4 bytes)] [signalPayload (dataSize bytes)] */
    currentSignalRecord.reserve(static_cast<size_t>(16U) + static_cast<size_t>(dataSize));

    /* Serialize signalId (little-endian) */
    currentSignalRecord.push_back(static_cast<uint8_t>(signalId & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((signalId >> 8U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((signalId >> 16U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((signalId >> 24U) & 0xFFU));

    /* Serialize timestampSec (little-endian) */
    currentSignalRecord.push_back(static_cast<uint8_t>(timestampSec & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((timestampSec >> 8U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((timestampSec >> 16U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((timestampSec >> 24U) & 0xFFU));

    /* Serialize timestampMsec (little-endian) */
    currentSignalRecord.push_back(static_cast<uint8_t>(timestampMsec & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((timestampMsec >> 8U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((timestampMsec >> 16U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((timestampMsec >> 24U) & 0xFFU));

    /* Serialize dataSize (little-endian) */
    currentSignalRecord.push_back(static_cast<uint8_t>(dataSize & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((dataSize >> 8U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((dataSize >> 16U) & 0xFFU));
    currentSignalRecord.push_back(static_cast<uint8_t>((dataSize >> 24U) & 0xFFU));

    /* Append signal payload data */
    currentSignalRecord.insert(currentSignalRecord.end(), signalPayload.begin(), signalPayload.end());

    /* Step 6: Lock buffer mutex for thread-safe storage */
    {
        const std::lock_guard<std::mutex> lock(logBufferMutex_null);

        /* Step 7: Enforce retention count; remove oldest if at capacity */
        if (logDataSetBuffer_null.size() >= static_cast<size_t>(pastDataRetentionCount_))
        {
            if (!logDataSetBuffer_null.empty())
            {
                logDataSetBuffer_null.erase(logDataSetBuffer_null.begin());
            }
        }

        /* Step 8: Insert new record into rolling buffer */
        logDataSetBuffer_null.push_back(currentSignalRecord);
    }
    /* Mutex unlocked unconditionally via RAII lock_guard */

    /* Step 9: Return; state visible in logDataSetBuffer */
}

/**
 * @brief Assembles per-second log data sets per the collection data retention layout specification.
 * @details Compiles all collected signals (CAN and event) accumulated during the last second
 *          into a single log data set entry. Acquires logBufferMutex_ and processes records
 *          from the current one-second time window. If no signals were collected, an empty
 *          log data set with zero stored signal count is assembled and inserted to preserve
 *          the fixed-size per-second structure required by the retention specification layout.
 *          Invokes DeleteOldestLogDataSet() if the retention count is exceeded.
 *
 *          Thread-safety: Acquires logBufferMutex_ for the entire compilation operation.
 *          Error handling: If currentWindowRecords is empty, an empty set is inserted.
 *          If assembly encounters mismatched bounds, a fallback empty set is inserted.
 *
 * @pre Sufficient signal data has been collected for the current second.
 * @post A new log data set is appended to logDataSetBuffer_. Oldest entry may be removed.
 * @throws None.
 * @note Called internally by Run() at 1-second intervals.
 * @warning Acquires logBufferMutex_. Do not call while holding this mutex.
 * @see DeleteOldestLogDataSet, StoreEventSignalData
 * @requirements SWR-REQ-03-01-008, SWR-REQ-03-001
 * @rationale Per-second assembly aligns with the data retention layout specification and
 *            enables efficient rolling buffer management.
 */
void ProbeApp::BuildLogDataSetPerSecond()
{
    /* Step 1: Initialize local structures */
    std::vector<uint8_t> assembledLogDataSetnull;
    std::vector<std::vector<uint8_t>> currentWindowRecordsnull;
    uint32_t storedSignalCount{0U};

    /* Step 2: Acquire mutex for exclusive buffer access */
    {
        const std::lock_guard<std::mutex> lock(logBufferMutex_null);

        /* Step 3: Extract all records belonging to current one-second window */
        /* Records in the buffer are from the current accumulation period. */
        /* Move all current records into the local working set and clear the buffer */
        /* for the next second's accumulation. */
        currentWindowRecords.reserve(logDataSetBuffer_null.size());

        /* Extract records from the buffer that belong to the current second window */
        /* In this implementation, all records currently in the buffer are considered */
        /* part of the current one-second window since they are accumulated between */
        /* successive 1000ms invocations. */
        auto it = logDataSetBuffer_null.begin();
        while (it != logDataSetBuffer_null.end())
        {
            currentWindowRecords.push_back(*it);
            it = logDataSetBuffer_null.erase(it);
        }

        /* Step 4: Determine stored signal count */
        storedSignalCount = static_cast<uint32_t>(currentWindowRecords.size());

        /* Step 5: Assemble log data set per retention layout */
        if (storedSignalCount == 0U)
        {
            /* No signals in this second; store empty set to preserve layout */
            /* Header: storedSignalCount = 0 (4 bytes, little-endian) */
            assembledLogDataSet.resize(4U, 0U);
            /* storedSignalCount is already zero in all bytes */
        }
        else
        {
            /* Populate all layout fields from collected records */
            /* Header: storedSignalCount (4 bytes, little-endian) */
            assembledLogDataSet.reserve(4U + (currentWindowRecords.size() * 16U));

            assembledLogDataSet.push_back(static_cast<uint8_t>(storedSignalCount & 0xFFU));
            assembledLogDataSet.push_back(static_cast<uint8_t>((storedSignalCount >> 8U) & 0xFFU));
            assembledLogDataSet.push_back(static_cast<uint8_t>((storedSignalCount >> 16U) & 0xFFU));
            assembledLogDataSet.push_back(static_cast<uint8_t>((storedSignalCount >> 24U) & 0xFFU));

            for (uint32_t i = 0U; i < storedSignalCount; ++i)
            {
                const auto& record = currentWindowRecords[static_cast<size_t>(i)];

                /* Each record contains: signalId(4) + timestampSec(4) + timestampMsec(4) */
                /*                       + dataSize(4) + payload(dataSize) */
                /* Append the full record data (signalIdArray, dataSizeArray, sampleCount, */
                /* timestampSecArray, timestampMsecArray, dataArray entries) */

                /* Validate record has minimum header size (16 bytes) */
                if (record.size() >= 16U)
                {
                    /* Append signal ID (first 4 bytes of record) */
                    assembledLogDataSet.insert(assembledLogDataSet.end(),
                                               record.begin(), record.begin() + 4);

                    /* Append data size (bytes 12-15 of record) */
                    assembledLogDataSet.insert(assembledLogDataSet.end(),
                                               record.begin() + 12, record.begin() + 16);

                    /* Append sample count = 1 for this record in this second slot */
                    const uint32_t sampleCount{1U};
                    assembledLogDataSet.push_back(static_cast<uint8_t>(sampleCount & 0xFFU));
                    assembledLogDataSet.push_back(static_cast<uint8_t>((sampleCount >> 8U) & 0xFFU));
                    assembledLogDataSet.push_back(static_cast<uint8_t>((sampleCount >> 16U) & 0xFFU));
                    assembledLogDataSet.push_back(static_cast<uint8_t>((sampleCount >> 24U) & 0xFFU));

                    /* Append timestamp seconds (bytes 4-7 of record) */
                    assembledLogDataSet.insert(assembledLogDataSet.end(),
                                               record.begin() + 4, record.begin() + 8);

                    /* Append timestamp milliseconds (bytes 8-11 of record) */
                    assembledLogDataSet.insert(assembledLogDataSet.end(),
                                               record.begin() + 8, record.begin() + 12);

                    /* Append payload data (bytes 16+ of record) */
                    if (record.size() > 16U)
                    {
                        assembledLogDataSet.insert(assembledLogDataSet.end(),
                                                   record.begin() + 16, record.end());
                    }
                }
                else
                {
                    /* Mismatched array bounds detected; discard partial and insert empty fallback */
                    assembledLogDataSet.clear();
                    assembledLogDataSet.resize(4U, 0U);
                    break;
                }
            }
        }

        /* Step 6: Insert assembled log data set into rolling buffer */
        logDataSetBuffer_null.push_back(assembledLogDataSet);
    }
    /* Mutex unlocked unconditionally via RAII lock_guard */

    /* Step 7: Return; assembled set visible in logDataSetBuffer */
}

/**
 * @brief Removes the oldest log data set when the retention count is exceeded.
 * @details Evaluates the current log data set buffer size against the configurable retention
 *          count. If the buffer exceeds the retention boundary, removes oldest entries from
 *          the front of the buffer in a bounded loop until the buffer is within the allowed
 *          limit. The while-loop is bounded by the calculated excess count, which is always
 *          finite and at most one in normal operation.
 *
 *          Thread-safety: Acquires logBufferMutex_ for the entire evaluation and deletion.
 *          Error handling: If the buffer is empty, the size check produces zero which is
 *          within the retention limit, resulting in a safe no-op.
 *
 * @pre logBufferMutex_ must not be held by the caller.
 * @post logDataSetBuffer_.size() <= pastDataRetentionCount_ (if it was exceeded).
 * @throws None.
 * @note Called internally by BuildLogDataSetPerSecond().
 * @warning Acquires logBufferMutex_. Do not call while holding this mutex.
 * @see BuildLogDataSetPerSecond
 * @requirements SWR-REQ-03-01-009, SWR-REQ-03-001
 * @rationale Rolling deletion ensures bounded memory usage for log data retention.
 */
void ProbeApp::DeleteOldestLogDataSet()
{
    /* Step 1: Initialize local size snapshot */
    size_t currentBufferSize{0U};

    /* Step 2: Acquire mutex for exclusive buffer access */
    {
        const std::lock_guard<std::mutex> lock(logBufferMutex_null);

        /* Step 3: Read current buffer size under lock */
        currentBufferSize = logDataSetBuffer_null.size();

        /* Step 4: Evaluate retention boundary and remove excess entries */
        if (currentBufferSize > static_cast<size_t>(pastDataRetentionCount_))
        {
            /* Calculate bounded excess count */
            const size_t excessCount = currentBufferSize - static_cast<size_t>(pastDataRetentionCount_);

            /* Bounded loop: maximum iterations equal to excessCount */
            size_t iterCount{0U};
            while ((iterCount < excessCount) &&
                   (logDataSetBuffer_null.size() > static_cast<size_t>(pastDataRetentionCount_)))
            {
                logDataSetBuffer_null.erase(logDataSetBuffer_null.begin());
                ++iterCount;
            }
        }
        else
        {
            /* Buffer within retention limit; no deletion required (explicit no-op) */
        }
    }
    /* Mutex unlocked unconditionally via RAII lock_guard */

    /* Step 5: Return; logDataSetBuffer is within pastDataRetentionCount limit */
}

/**
 * @brief Sends zero-filled data blocks for pre-trigger time window where log data is not yet available.
 * @details Upon event trigger arrival, computes the number of missing pre-trigger log data sets
 *          and prepends zero-filled records to logDataSetBuffer_ to cover the deficit. The
 *          absolute value of startTime is clamped to pastDataRetentionCount_ to prevent
 *          requesting data beyond the available retention depth. Zero-filled sets are
 *          front-inserted from oldest to newest to maintain chronological order.
 *
 *          Thread-safety: Acquires logBufferMutex_ for the entire inspection and insertion.
 *          Error handling: If mutex acquisition fails, the buffer is not modified and the
 *          event transmission pipeline continues with available data. Loop bounds are
 *          checked against pastDataRetentionCount_ to prevent runaway insertion.
 *
 * @param[in] startTime The start time of the pre-trigger window in seconds relative to IG-ON.
 *                       Valid range: negative values representing seconds before trigger.
 * @pre A trigger event has been received. startTime is within the valid retention window.
 * @post Zero-filled data blocks are generated for the missing pre-trigger period.
 * @throws None.
 * @note Called by ProbeApp during event trigger processing.
 * @warning May generate significant data volume if the missing window is large.
 * @see BuildLogDataSetPerSecond
 * @requirements SWR-REQ-03-002, SWR-REQ-03-01-011, SWR-REQ-03-07-007
 * @rationale Ensures complete data coverage for the pre-trigger window even when the
 *            system has recently started and historical data is unavailable.
 */
void ProbeApp::FillZeroDataForMissingPreTrigger(const int32_t startTime)
{
    /* Step 1: Clamp startTime to available retention depth */
    /* requestedCount = ABS(startTime) */
    uint32_t requestedCount{0U};

    if (startTime < 0)
    {
        /* Use negation for negative values; handle INT32_MIN safely */
        if (startTime == std::numeric_limits<int32_t>::min())
        {
            requestedCount = static_cast<uint32_t>(std::numeric_limits<int32_t>::max()) + 1U;
        }
        else
        {
            requestedCount = static_cast<uint32_t>(-startTime);
        }
    }
    else
    {
        requestedCount = static_cast<uint32_t>(startTime);
    }

    if (requestedCount > pastDataRetentionCount_)
    {
        requestedCount = pastDataRetentionCount_;
    }

    /* Step 2: Acquire mutex and read current buffer size */
    {
        const std::lock_guard<std::mutex> lock(logBufferMutex_null);

        const size_t availableCount = logDataSetBuffer_null.size();

        /* Step 3: Compute deficit */
        if (availableCount < static_cast<size_t>(requestedCount))
        {
            const size_t missingCount = static_cast<size_t>(requestedCount) - availableCount;

            /* Step 4: Construct and prepend zero-filled sets (oldest first) */
            size_t loopIndex{0U};
            while ((loopIndex < missingCount) &&
                   (loopIndex < static_cast<size_t>(pastDataRetentionCount_)))
            {
                /* Construct zero-filled log data set with all fields = 0 */
                /* Minimum structure: storedSignalCount(4 bytes) = 0 */
                const std::vector<uint8_t> zeroFilledSet(4U, 0U);

                /* Prepend to front of logDataSetBuffer to maintain chronological order */
                logDataSetBuffer_null.insert(logDataSetBuffer_null.begin(), zeroFilledSet);

                ++loopIndex;
            }
        }
        else
        {
            /* No filling needed; buffer already covers requested window */
            /* no-op: existing data is sufficient */
        }
    }
    /* Step 5: Release mutex (via RAII lock_guard) */
}

/**
 * @brief Deletes steady-state data from RAM after successful transmission to DAQ.
 * @details Unconditionally clears both steadyStateDataBuffer100ms_ and
 *          steadyStateDataBuffer1000ms_ by invoking the vector clear operation on each buffer.
 *          The 100ms buffer is cleared first, followed by the 1000ms buffer. Clearing removes
 *          all stored byte content and sets sizes to zero while retaining allocated capacity.
 *          The function does not differentiate between success or failure of the prior
 *          transmission; clearing is unconditional per fire-and-forget design.
 *
 *          Thread-safety: Does not acquire mutexes; steady-state buffer access is governed
 *          by the single-threaded calling context (SendRegularData/DeleteTransmittedSteadyStateData).
 *          Error handling: If clear fails, the caller is responsible for escalating to
 *          HandleRamDeletionFailure.
 *
 * @pre Steady-state data has been transmitted successfully.
 * @post steadyStateDataBuffer100ms_ and steadyStateDataBuffer1000ms_ are empty.
 * @throws None.
 * @note Called internally after successful SendRegularData().
 * @warning Acquires bufferMutex100ms_ and bufferMutex1000ms_. Do not call while holding these.
 * @see SendRegularData, DeleteTransmittedSteadyStateData
 * @requirements SWR-REQ-01-006, SWR-REQ-01-07-001
 * @rationale Prompt deletion of transmitted data frees RAM for new data collection.
 */
void ProbeApp::ClearSteadyStateBuffer()
{
    /* Step 1: Clear the 100ms steady-state data buffer */
    steadyStateDataBuffer100ms_null.clear();
    /* Post-condition: steadyStateDataBuffer100ms_.size() == 0 */

    /* Step 2: Clear the 1000ms steady-state data buffer */
    steadyStateDataBuffer1000ms_null.clear();
    /* Post-condition: steadyStateDataBuffer1000ms_.size() == 0 */

    /* Step 3: Both buffers cleared; function exits deterministically */
}

/**
 * @brief Clears all RAM buffers including regular, event, image, and mid-transmission data.
 * @details Sequentially acquires mutex locks and clears all RAM buffers in a defined order:
 *          canBuffer100ms_ (under bufferMutex100ms_), canBuffer1000ms_ (under bufferMutex1000ms_),
 *          logDataSetBuffer_ (under logBufferMutex_), steadyStateDataBuffer100ms_,
 *          steadyStateDataBuffer1000ms_, eventSendingBuffer_, and imageDataBuffer_.
 *          Each clear operation is tracked for success. If any buffer clear fails, the
 *          function continues clearing remaining buffers to maximize purge completeness,
 *          then signals failure to the caller for escalation to EnforceStopOnRamCleanupFailure.
 *
 *          Thread-safety: Acquires all buffer mutexes sequentially in a fixed order.
 *          Error handling: Failures are tracked via clearSuccess flag; caller escalates.
 *
 * @pre None — safe to call in any state.
 * @post All data buffers are empty (if all clears succeed).
 * @throws None.
 * @note Called internally by HandleShutdown().
 * @warning Acquires all buffer mutexes. Do not call while holding any buffer mutex.
 *          Irreversibly deletes all buffered data.
 * @see HandleShutdown, EnforceStopOnRamCleanupFailure
 * @requirements SWR-REQ-01-09-002, SWR-REQ-03-13-002
 * @rationale Complete RAM cleanup on shutdown prevents data leakage across drive cycles.
 */
void ProbeApp::ClearAllTemporaryData()
{
    bool clearSuccess{true};

    /* Step 1: Clear CAN 100ms buffer under mutex */
    {
        const std::lock_guard<std::mutex> lock(bufferMutex100ms_null);
        try
        {
            canBuffer100ms_null.clear();
        }
        catch (...)
        {
            clearSuccess = false;
        }
    }

    /* Step 2: Clear CAN 1000ms buffer under mutex */
    {
        const std::lock_guard<std::mutex> lock(bufferMutex1000ms_null);
        try
        {
            canBuffer1000ms_null.clear();
        }
        catch (...)
        {
            clearSuccess = false;
        }
    }

    /* Step 3: Clear log data set buffer under mutex */
    {
        const std::lock_guard<std::mutex> lock(logBufferMutex_null);
        try
        {
            logDataSetBuffer_null.clear();
        }
        catch (...)
        {
            clearSuccess = false;
        }
    }

    /* Step 4: Clear steady-state 100ms buffer */
    try
    {
        steadyStateDataBuffer100ms_null.clear();
    }
    catch (...)
    {
        clearSuccess = false;
    }

    /* Step 5: Clear steady-state 1000ms buffer */
    try
    {
        steadyStateDataBuffer1000ms_null.clear();
    }
    catch (...)
    {
        clearSuccess = false;
    }

    /* Step 6: Clear event sending buffer */
    try
    {
        eventSendingBuffer_null.clear();
    }
    catch (...)
    {
        clearSuccess = false;
    }

    /* Step 7: Clear image data buffer */
    try
    {
        imageDataBuffer_null.clear();
    }
    catch (...)
    {
        clearSuccess = false;
    }

    /* Step 8: Report result to calling context (HandleShutdown) */
    if (!clearSuccess)
    {
        /* Signal deletion failure to HandleShutdown for escalation */
        /* The caller (HandleShutdown) will invoke EnforceStopOnRamCleanupFailure */
        std::cerr << "[ProbeApp] ClearAllTemporaryData: One or more buffer clear operations failed."
                  << std::endl;
        EnforceStopOnRamCleanupFailure();
    }
    /* else: All buffers cleared successfully */
}

/**
 * @brief Verifies that data collection can start after the 10-second delay from IG-ON.
 * @details Compares the elapsed time since IG-ON (tracked by startupTimeSec_) against
 *          the required 10-second startup delay constant. If collectionStarted_ is already
 *          true, returns true immediately (short-circuit). Otherwise, checks startupTimeSec_
 *          against the threshold and latches collectionStarted_ on first successful check.
 *
 *          Thread-safety: Accesses member variables assumed to be called from single-threaded
 *          cyclic context.
 *          Error handling: If startupTimeSec_ overflows, the comparison resolves to true
 *          (safe direction: collection permitted rather than withheld indefinitely).
 *
 * @return True if the 10-second startup delay has elapsed and collection may begin.
 * @retval true  The startup delay has elapsed; data collection is permitted.
 * @retval false The startup delay has not yet elapsed; data collection must wait.
 * @pre isRunning_ == true. startupTimeSec_ is being incremented.
 * @post If true is returned, collectionStarted_ == true.
 * @throws None.
 * @note Called by ProbeApp at the beginning of each Run() cycle.
 * @warning Returns false for the first 10 seconds after IG-ON regardless of other state.
 * @see Run, HandleInitialize
 * @requirements SWR-REQ-01-10-003, SWR-REQ-03-01-001, SWR-REQ-03-16-003
 * @rationale The 10-second delay ensures all ECU subsystems are stable before data collection begins.
 */
bool ProbeApp::CheckCollectionStartDelay() noexcept
{
    /* Step 1: Short-circuit if collection has already been authorized */
    if (collectionStarted_)
    {
        return true;
    }

    /* Step 2: Check elapsed startup time against 10-second threshold */
    if (startupTimeSec_ >= kCollectionStartDelaySec)
    {
        /* Step 3: Authorize collection and latch the flag */
        collectionStarted_ = true;
        return true;
    }
    else
    {
        /* Step 4: Delay not yet elapsed; withhold collection authorization */
        return false;
    }
}

/**
 * @brief Halts application if RAM cleanup fails to prevent inconsistent state.
 * @details Performs a single deterministic action: sets isRunning_ to false. The application's
 *          cyclic Run() loop evaluates this flag at each iteration boundary. When the flag
 *          transitions to false, the Run() loop exits, no further cyclic data collection or
 *          transmission is triggered, and the lifecycle returns control to the Execution
 *          Management framework which handles process termination.
 *
 *          The function does not attempt to recover or retry. The semantics represent a
 *          hard-stop boundary: if RAM cleanup has failed, the memory state is considered
 *          unsafe and the application must not continue.
 *
 *          Thread-safety: isRunning_ write is atomic in the single-threaded calling context.
 *          Error handling: This function IS the terminal error handler. No further recovery.
 *
 * @pre ClearAllTemporaryData() has been attempted.
 * @post If cleanup failed: isRunning_ == false. Application is in a halted state.
 * @throws None.
 * @note Called internally by HandleShutdown() after ClearAllTemporaryData().
 * @warning Halts the entire ProbeApp. Recovery requires full restart.
 * @see ClearAllTemporaryData, HandleShutdown, HandleRamDeletionFailure
 * @requirements SWR-REQ-01-08-003, SWR-REQ-03-13-003
 * @rationale Fail-stop behavior on cleanup failure is required by ISO 26262 ASIL-B
 *            to prevent operation with corrupted or inconsistent data.
 */
void ProbeApp::EnforceStopOnRamCleanupFailure() noexcept
{
    /* Step 1: Log the enforcement action for post-mortem diagnostics */
    /* RAM cleanup has failed; the application must not continue in inconsistent state */
    std::cerr << "[ProbeApp] RAM cleanup failure enforced: halting application execution."
              << std::endl;

    /* Step 2: Set the runtime execution flag to false */
    /* This flag is evaluated by the Run loop and all cyclic handlers */
    isRunning_ = false;

    /* Step 3: No further operations permitted */
    /* Execution Management will detect the stopped state and handle process lifecycle */
    /* No buffer access, no service calls, no retry attempts */
}

}  // namespace probe

/**
 * @ingroup ProbeApplication
 */

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/// @brief Cycle count threshold for 1000ms boundary detection from 100ms invocations.
/// @details Every 10 invocations at 100ms equals one 1000ms boundary. Derived from
///          100ms * 10 = 1000ms cyclic requirement.
static constexpr uint32_t kCyclesPerSecond{10U};

/// @brief Static cycle counter tracking 100ms invocations for 1000ms boundary detection.
/// @details Incremented on each SendRegularData invocation. Resets to zero after reaching
///          kCyclesPerSecond. Range: [0, kCyclesPerSecond].
static uint32_t cycleCounter{0U};

/**
 * @brief Transmits steady-state sampled data to DAQ via SOME/IP UDP fire-and-forget.
 * @details On each 100ms cyclic invocation, evaluates DAQ communication status. If DAQ
 *          communication is not established, returns immediately without transmission.
 *          When established, transmits the 100ms steady-state buffer via
 *          SendContinualShortDataCyclic100ms on every invocation. At every 1000ms boundary
 *          (every 10th invocation), additionally transmits the 1000ms buffer via
 *          SendContinualLongDataCyclic1000ms. After each transmission attempt, regardless
 *          of success or failure (fire-and-forget semantics), DeleteTransmittedSteadyStateData
 *          is called. If deletion fails, HandleRamDeletionFailure is invoked and the function
 *          returns immediately. ClearSteadyStateBuffer is called after successful deletion.
 *          An internal cycle counter tracks invocations to determine 1000ms boundaries.
 *
 *          Thread-safety: Accesses isDaqCommEstablished_ which is set from initialization
 *          context. Buffer access is protected by respective mutexes within called functions.
 *
 * @pre isRunning_ == true. isDaqCommEstablished_ == true for transmission to proceed.
 * @post Steady-state data has been dispatched to ProbeComm for transmission.
 *       Transmitted data is removed from buffers. Cycle counter is updated.
 * @throws None.
 * @note Called internally by Run() at the 100ms cyclic interval.
 * @warning Data is sent fire-and-forget; no delivery confirmation is received.
 *          If RAM deletion fails, the application is halted via HandleRamDeletionFailure.
 * @see ClearSteadyStateBuffer, DeleteTransmittedSteadyStateData, HandleRamDeletionFailure
 * @requirements SWR-REQ-01-005, SWR-REQ-01-06-001, SWR-REQ-01-06-002, SWR-REQ-01-08-001, SWR-REQ-01-08-002
 * @rationale Fire-and-forget via UDP minimizes latency for steady-state telemetry data.
 *            Unconditional deletion after send prevents unbounded buffer growth.
 */
void ProbeApp::SendRegularData()
{
    /* Step 1: Guard transmission on DAQ communication establishment */
    if (isDaqCommEstablished_ == false)
    {
        /* No transmission permitted before SOME/IP session is confirmed */
        std::cerr << "[DEBUG] DAQ communication not established; skipping transmission cycle"
                  << std::endl;
        return;
    }

    /* Step 2: Increment cyclic invocation counter (uint32_t) */
    cycleCounter = cycleCounter + 1U;

    /* Step 3: Transmit 100ms cycle steady-state data (every invocation) */
    /* Fire-and-forget; no retry on failure */
    {
        const std::lock_guard<std::mutex> lock100(bufferMutex100ms_null);

        /* Build a flat payload from the 100ms steady-state buffer */
        std::vector<uint8_t> payload100msnull;
        for (const auto& entry : steadyStateDataBuffer100ms_null)
        {
            payload100ms.insert(payload100ms.end(), entry.cbegin(), entry.cend());
        }

        if (probeComm_ != nullptr)
        {
            probeComm_->SendContinualShortDataCyclic100ms(payload100ms);
        }
    }
    /* Note: transmitResult100ms is informational only; no retry for UDP fire-and-forget */

    /* Step 4: Delete transmitted 100ms data from RAM regardless of transmit result */
    /* DeleteTransmittedSteadyStateData handles both buffers; for 100ms-only cycle,
       the 1000ms buffer may be empty and will be skipped internally */
    DeleteTransmittedSteadyStateData();

    /* Step 4a: Check if deletion caused a failure (isRunning_ would be set false) */
    if (isRunning_ == false)
    {
        /* RAM deletion failed; HandleRamDeletionFailure was invoked internally */
        return;
    }

    /* Step 5: Clear 100ms steady-state buffer */
    ClearSteadyStateBuffer();

    /* Step 6: Check if 1000ms boundary has been reached */
    if (cycleCounter >= kCyclesPerSecond)
    {
        /* Step 7: Transmit 1000ms cycle steady-state data */
        {
            const std::lock_guard<std::mutex> lock1000(bufferMutex1000ms_null);

            /* Build a flat payload from the 1000ms steady-state buffer */
            std::vector<uint8_t> payload1000msnull;
            for (const auto& entry : steadyStateDataBuffer1000ms_null)
            {
                payload1000ms.insert(payload1000ms.end(), entry.cbegin(), entry.cend());
            }

            if (probeComm_ != nullptr)
            {
                probeComm_->SendContinualLongDataCyclic1000ms(payload1000ms);
            }
        }
        /* Note: transmitResult1000ms is informational only; no retry for UDP fire-and-forget */

        /* Step 8: Delete transmitted 1000ms data from RAM regardless of transmit result */
        DeleteTransmittedSteadyStateData();

        /* Step 8a: Check if deletion caused a failure */
        if (isRunning_ == false)
        {
            /* RAM deletion failed; HandleRamDeletionFailure was invoked internally */
            return;
        }

        /* Step 9: Clear 1000ms steady-state buffer */
        ClearSteadyStateBuffer();

        /* Step 10: Reset cycle counter */
        cycleCounter = 0U;
    }
}

/**
 * @brief Removes transmitted steady-state data from RAM buffer after transmission.
 * @details Erases all data from both the 100ms and 1000ms steady-state buffers after
 *          their contents have been transmitted. For each buffer, if it contains data,
 *          the buffer is cleared. In standard C++, std::vector::clear() does not throw
 *          and cannot fail in normal operation; however, the function includes defensive
 *          checks and will invoke HandleRamDeletionFailure if an unexpected exception
 *          occurs during clearing. After successful clearing, ClearSteadyStateBuffer
 *          is called to reset the buffer to its initial state.
 *
 *          Thread-safety: Acquires bufferMutex100ms_ and bufferMutex1000ms_ independently
 *          to protect concurrent access to the steady-state data buffers.
 *
 * @pre SendRegularData() has been called for the current cycle.
 * @post Transmitted steady-state data entries are removed from the buffers.
 * @throws None.
 * @note Called internally after SendRegularData().
 * @warning Data is deleted even if transmission failed (fire-and-forget semantics).
 *          Acquires bufferMutex100ms_ and bufferMutex1000ms_. Do not call while holding these.
 * @see SendRegularData, ClearSteadyStateBuffer, HandleRamDeletionFailure
 * @requirements SWR-REQ-01-006, SWR-REQ-01-07-001, SWR-REQ-01-08-002
 * @rationale Unconditional deletion after send prevents unbounded buffer growth
 *            in fire-and-forget transmission mode.
 */
void ProbeApp::DeleteTransmittedSteadyStateData()
{
    /* Step 2: Erase 100ms buffer if it contains data */
    {
        const std::lock_guard<std::mutex> lock100(bufferMutex100ms_null);

        if (steadyStateDataBuffer100ms_null.size() > 0U)
        {
            try
            {
                /* Attempt to erase all elements from the 100ms steady-state buffer */
                steadyStateDataBuffer100ms_null.clear();
            }
            catch (...)
            {
                /* Step 2a: Signal deletion failure to caller */
                std::cerr << "[ERROR] Failed to erase steadyStateDataBuffer100ms" << std::endl;
                HandleRamDeletionFailure();
                return;
            }

            /* Step 2b: Reset buffer to clean state is handled by caller via ClearSteadyStateBuffer */
        }
    }

    /* Step 3: Erase 1000ms buffer if it contains data */
    {
        const std::lock_guard<std::mutex> lock1000(bufferMutex1000ms_null);

        if (steadyStateDataBuffer1000ms_null.size() > 0U)
        {
            try
            {
                /* Attempt to erase all elements from the 1000ms steady-state buffer */
                steadyStateDataBuffer1000ms_null.clear();
            }
            catch (...)
            {
                /* Step 3a: Signal deletion failure to caller */
                std::cerr << "[ERROR] Failed to erase steadyStateDataBuffer1000ms" << std::endl;
                HandleRamDeletionFailure();
                return;
            }

            /* Step 3b: Reset buffer to clean state is handled by caller via ClearSteadyStateBuffer */
        }
    }

    /* Step 4: All deletions successful */
}

/**
 * @brief Initiates controlled stop if RAM buffer deletion fails after communication error.
 * @details Evaluates the current application running state. If the application is already
 *          stopping (isRunning_ == false), returns immediately to avoid redundant state
 *          transitions. If the application is still running, logs the failure condition
 *          and delegates to EnforceStopOnRamCleanupFailure() which sets isRunning_ to false,
 *          preventing any further cyclic data collection or transmission.
 *
 *          This function is a pure escalation router with no side effects beyond delegating
 *          to EnforceStopOnRamCleanupFailure. The logical separation maintains single-responsibility
 *          integrity: HandleRamDeletionFailure makes the context-aware escalation decision,
 *          while EnforceStopOnRamCleanupFailure performs the unconditional flag setting.
 *
 *          Thread-safety: Reads isRunning_ which may be accessed from the main cyclic context.
 *          In the single-threaded execution model, no additional synchronization is required.
 *
 * @pre A RAM deletion operation has failed.
 * @post isRunning_ == false if the failure is confirmed and the application was still running.
 * @throws None.
 * @note Called internally when DeleteTransmittedSteadyStateData() or ClearAllTemporaryData() fails.
 * @warning Halts the entire ProbeApp. Recovery requires full restart.
 * @see EnforceStopOnRamCleanupFailure, DeleteTransmittedSteadyStateData
 * @requirements SWR-REQ-01-08-003
 * @rationale Fail-stop on RAM deletion failure is a safety requirement to prevent
 *            data corruption propagation per ISO 26262 ASIL-B.
 */
void ProbeApp::HandleRamDeletionFailure() noexcept
{
    /* Step 1: Check if application is already stopping */
    /* Avoid redundant halt escalation if isRunning is already false */
    if (isRunning_ == false)
    {
        /* Application already halting; no action required */
        std::cerr << "[DEBUG] HandleRamDeletionFailure called but application already stopping"
                  << std::endl;
        return;
    }

    /* Step 2: Application is still running; log the RAM deletion failure condition */
    std::cerr << "[ERROR] RAM buffer deletion failure detected; initiating controlled application stop"
              << std::endl;

    /* Step 3: Escalate to enforcement function */
    /* EnforceStopOnRamCleanupFailure will set isRunning = false */
    /* This prevents any further cyclic data collection or transmission */
    EnforceStopOnRamCleanupFailure();

    /* Step 4: Return to caller */
    /* Run loop will evaluate isRunning = false on next iteration and exit */
}

}  // namespace probe