/**
 * @file   ProbeCommVariant.cpp
 * @brief  Implementation of ProbeCommVariant component.
 * @details Portable C++ implementation generated by
 *          the Code Generation Pipeline.
 *          Uses runtime::IRuntime for all platform-dependent behavior.
 * @author  Engineering Team
 * @version 1.0.0
 * @copyright Copyright (c) 2024 Company. All rights reserved.
 */

#include "ProbeCommVariant/ProbeCommVariant.hpp"
#include <array>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>

// ============================================================
// Internal abstractions for SharedMemory_VariantCode and
// variant dictionary — defined here to satisfy the pseudocode
// execution guarantee without external AUTOSAR/ara dependencies.
// ============================================================

namespace {

/**
 * @struct  SharedMemReadResult
 * @brief   Result type returned by the SharedMemory_VariantCode Read() abstraction.
 * @details Encapsulates the outcome of a shared-memory read operation: a success flag
 *          and the string value retrieved from the shared memory segment.
 * @ingroup ProbeCommVariantGroup
 * @note    Plain aggregate — no invariants beyond member initialisation.
 */
struct SharedMemReadResult
{
    bool        success{false};  ///< @brief True if the read operation succeeded; false otherwise.
    std::string value;           ///< @brief The variant code string read from shared memory. Valid only when success == true.
};

/**
 * @struct  DictionaryEntry
 * @brief   Represents a single resolved entry from the variant dictionary.
 * @details Holds the found flag and per-feature activation strings for one variant code.
 *          Each value field contains "A" when the feature is active, or any other string
 *          when it is inactive.
 * @ingroup ProbeCommVariantGroup
 * @note    Plain aggregate — no invariants beyond member initialisation.
 */
struct DictionaryEntry
{
    bool        found{false};                          ///< @brief True if the variant code was located in the dictionary.
    std::string regularProbeValue;                     ///< @brief Activation string for regular probe. "A" == enabled.
    std::string eventProbeValue;                       ///< @brief Activation string for event probe. "A" == enabled.
    std::string eventProbeWithoutPictureValue;         ///< @brief Activation string for event probe without picture. "A" == enabled.
    std::string gedrValue;                             ///< @brief Activation string for GEDR. "A" == enabled.
    std::string gedrWithoutPictureValue;               ///< @brief Activation string for GEDR without picture. "A" == enabled.
};

/**
 * @struct  DictionaryLoadResult
 * @brief   Result type returned by LoadDictionary(), carrying the parsed variant table.
 * @details Contains a success flag and the in-memory representation of the variant
 *          dictionary. The FindEntry() method performs a lookup by variant code string.
 * @ingroup ProbeCommVariantGroup
 * @note    Plain aggregate — no invariants beyond member initialisation.
 */
struct DictionaryLoadResult
{
    bool success{false};  ///< @brief True if the dictionary file was successfully loaded and parsed.

    /**
     * @brief   In-memory variant table: maps 5-char code to per-feature activation strings.
     * @details Key   = 5-character variant code string.
     *          Value = array of 5 activation strings in order:
     *                  [0] regularProbe, [1] eventProbe, [2] eventProbeWithoutPicture,
     *                  [3] gedr, [4] gedrWithoutPicture.
     */
    std::unordered_map<std::string, std::array<std::string, 5U>> table;

    /**
     * @brief   Searches the loaded dictionary for the supplied variant code.
     * @details Performs an O(1) average-case lookup in the hash map. Returns a populated
     *          DictionaryEntry when the code is found, or a default-constructed entry
     *          (found == false) when it is absent.
     * @param[in] code  The 5-character variant code to search for. Must be a valid std::string.
     * @return  DictionaryEntry with found == true and populated value fields on success,
     *          or found == false on failure.
     * @retval  DictionaryEntry{found=true, ...}   Code located in the dictionary.
     * @retval  DictionaryEntry{found=false, ...}  Code not present in the dictionary.
     * @throws  None.
     * @pre     success == true before calling FindEntry.
     * @post    No state is modified.
     */
    DictionaryEntry FindEntry(const std::string& code) const noexcept
    {
        DictionaryEntry entry;
        const auto it = table.find(code);
        if (it != table.cend())
        {
            entry.found                        = true;
            entry.regularProbeValue            = it->second[0U];
            entry.eventProbeValue              = it->second[1U];
            entry.eventProbeWithoutPictureValue = it->second[2U];
            entry.gedrValue                    = it->second[3U];
            entry.gedrWithoutPictureValue      = it->second[4U];
        }
        return entry;
    }
};

/**
 * @brief   Reads the variant code from the shared memory segment.
 * @details Implements the SharedMemory_VariantCode.Read() abstraction. Opens the shared
 *          memory backing file (or platform shared memory region) identified by the
 *          well-known key "SharedMemory_VariantCode", reads exactly
 *          ProbeCommVariant::kVariantCodeLength bytes, and returns them as a std::string.
 *          On any I/O failure the returned result has success == false and value == "".
 * @return  SharedMemReadResult with success == true and a 5-character value on success,
 *          or success == false and empty value on failure.
 * @retval  SharedMemReadResult{true,  "<5-char code>"}  Read succeeded.
 * @retval  SharedMemReadResult{false, ""}               Read failed or data malformed.
 * @throws  None — all exceptions are caught internally.
 * @pre     The shared memory segment must have been initialised by the boot software.
 * @post    No persistent state is modified.
 * @note    In a bare-metal environment this would map to a fixed memory address read.
 *          Here a POSIX file-backed shared memory path is used as the portable equivalent.
 */
SharedMemReadResult SharedMemory_VariantCode_Read() noexcept
{
    SharedMemReadResult result;

    // Attempt to open the shared memory backing file.
    // On bare-metal this maps to a fixed-address memory read.
    std::ifstream sharedMemFile{"/dev/shm/SharedMemory_VariantCode",
                                std::ios::in | std::ios::binary};
    if (!sharedMemFile.is_open())
    {
        result.success = false;
        result.value   = std::string{};
        return result;
    }

    std::string readBuffer(probe::ProbeCommVariant::kVariantCodeLength, '\0');
    sharedMemFile.read(&readBuffer[0],
                       static_cast<std::streamsize>(probe::ProbeCommVariant::kVariantCodeLength));

    if (sharedMemFile.gcount() !=
        static_cast<std::streamsize>(probe::ProbeCommVariant::kVariantCodeLength))
    {
        result.success = false;
        result.value   = std::string{};
        return result;
    }

    result.success = true;
    result.value   = readBuffer;
    return result;
}

/**
 * @brief   Loads and parses the variant dictionary from the configuration file.
 * @details Opens the file at the supplied path and parses each non-empty, non-comment line
 *          as a CSV record with the format:
 *              CODE,regularProbe,eventProbe,eventProbeWithoutPicture,gedr,gedrWithoutPicture
 *          where each feature column contains "A" (active) or any other token (inactive).
 *          Lines beginning with '#' are treated as comments and skipped.
 *          Returns a DictionaryLoadResult with success == false if the file cannot be opened
 *          or contains no valid entries.
 * @param[in] path  File-system path to the variant dictionary configuration file.
 *                  Must be a valid, null-terminated path string. Range: non-empty string.
 * @return  DictionaryLoadResult with success == true and a populated table on success,
 *          or success == false and an empty table on failure.
 * @retval  DictionaryLoadResult{true,  <populated table>}  File loaded and parsed successfully.
 * @retval  DictionaryLoadResult{false, <empty table>}       File not found or parse error.
 * @throws  None — all exceptions are caught internally.
 * @pre     path must refer to a readable file in the expected CSV format.
 * @post    No persistent state is modified.
 */
DictionaryLoadResult LoadDictionary(const std::string& path) noexcept
{
    DictionaryLoadResult result;

    std::ifstream dictFile{path, std::ios::in};
    if (!dictFile.is_open())
    {
        result.success = false;
        return result;
    }

    std::string line;
    while (std::getline(dictFile, line))
    {
        // Skip empty lines and comment lines.
        if (line.empty() || (line[0] == '#'))
        {
            continue;
        }

        std::istringstream lineStream{line};
        std::array<std::string, 6U> fields;
        bool parseOk{true};

        for (std::size_t i{0U}; i < 6U; ++i)
        {
            if (!std::getline(lineStream, fields[i], ','))
            {
                parseOk = false;
                break;
            }
        }

        if (!parseOk || fields[0U].empty())
        {
            continue;
        }

        std::array<std::string, 5U> featureValues{
            fields[1U],  // regularProbe
            fields[2U],  // eventProbe
            fields[3U],  // eventProbeWithoutPicture
            fields[4U],  // gedr
            fields[5U]   // gedrWithoutPicture
        };

        result.table.emplace(fields[0U], featureValues);
    }

    result.success = !result.table.empty();
    return result;
}

} // anonymous namespace

// ============================================================
// namespace probe — ProbeCommVariant implementations
// ============================================================

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

// ============================================================
// ProbeCommVariant — Constructor (PV-001)
// ============================================================

/**
 * @brief   Constructs the variant configuration manager with safe default values.
 * @details Initialises all feature-flag members to false, sets variantCode_null and
 *          defaultVariantCode_null to empty strings (kDefaultVariantCode), sets
 *          variantDictionaryPath_null to kVariantDictionaryPath, and sets
 *          variantReadSuccess_ to false. No shared-memory access is performed in the
 *          constructor; that is deferred to ReadVariantCode() to allow controlled startup
 *          sequencing by ProbeApp. The variantDictionary_null map is default-constructed
 *          as an empty map.
 * @pre     None — default-constructible with no external dependencies.
 * @post    All feature flags are false. variantCode_null == "". variantReadSuccess_ == false.
 *          variantDictionaryPath_null == kVariantDictionaryPath.
 * @throws  None — constructor is noexcept.
 * @note    Called by: ProbeApp. Call condition: Startup.
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 * @rationale Deferred initialisation pattern ensures the constructor cannot fail,
 *            simplifying error handling at the call site.
 */
ProbeCommVariant::ProbeCommVariant() noexcept
    : variantCode_null{kDefaultVariantCode}
    , defaultVariantCode_null{kDefaultVariantCode}
    , variantReadSuccess_{false}
    , regularProbeEnabled_{false}
    , eventProbeEnabled_{false}
    , eventProbeWithoutPictureEnabled_{false}
    , gedrEnabled_{false}
    , gedrWithoutPictureEnabled_{false}
    , daqTransmissionEnabled_{false}
    , variantDictionaryPath_null{kVariantDictionaryPath}
{
    // All members are initialised via the member-initialiser list above.
    // No external service interaction is performed during construction.
}

// ============================================================
// ~ProbeCommVariant — Destructor (PV-002)
// ============================================================

/**
 * @brief   Destroys the variant configuration manager and releases all resources.
 * @details Performs an orderly teardown. All std::string members (variantCode_null,
 *          defaultVariantCode_null, variantDictionaryPath_null) are released by standard
 *          C++ RAII semantics when they go out of scope. The variantDictionary_null
 *          unordered_map is also released by RAII. All boolean primitive members
 *          (regularProbeEnabled_, eventProbeEnabled_, eventProbeWithoutPictureEnabled_,
 *          gedrEnabled_, gedrWithoutPictureEnabled_, daqTransmissionEnabled_,
 *          variantReadSuccess_) require no explicit release. No external service calls
 *          or I/O operations are performed during destruction. Destruction completes
 *          deterministically within bounded execution time.
 * @pre     Object must have been fully constructed.
 * @post    All resources held by this instance are released.
 * @throws  None — destructor is noexcept.
 * @note    Called by: ProbeApp.
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 */
ProbeCommVariant::~ProbeCommVariant() noexcept
{
    // All std::string members are automatically released by RAII:
    //   variantCode_null, defaultVariantCode_null, variantDictionaryPath_null
    //   go out of scope and their destructors are invoked automatically.
    // variantDictionary_null (std::unordered_map) is also released by RAII.
    // All boolean flags are primitive types; no explicit release is needed:
    //   regularProbeEnabled_, eventProbeEnabled_, eventProbeWithoutPictureEnabled_,
    //   gedrEnabled_, gedrWithoutPictureEnabled_, daqTransmissionEnabled_,
    //   variantReadSuccess_ are released automatically.
    // No external service interaction during destruction.
    // Destruction completes deterministically.
}

// ============================================================
// ReadVariantCode (PV-003)
// ============================================================

/**
 * @brief   Reads the 5-byte variant code from shared memory during initialisation.
 * @details Implements the SharedMemory_VariantCode provided interface. Calls
 *          SharedMemory_VariantCode.Read() and stores the result in the local variable
 *          readResult. If readResult.success is true, variantCode_null is assigned
 *          readResult.value and variantReadSuccess_ is set to true. If readResult.success
 *          is false, variantCode_null is assigned defaultVariantCode_null and
 *          variantReadSuccess_ is set to false, and a LOG_ERROR diagnostic is emitted to
 *          std::cerr. SetVariant() is then called with variantCode_null to apply feature
 *          flags. The function returns variantCode_null to the caller.
 * @return  std::string containing the raw variant code read from shared memory,
 *          or an empty string on failure.
 * @retval  Non-empty 5-character string  Variant code successfully read from shared memory.
 * @retval  Empty string                  Read failed or data length invalid; fallback applied.
 * @pre     Shared memory segment must be initialised and accessible.
 * @post    variantCode_null holds the read value or empty string. variantReadSuccess_ reflects outcome.
 *          SetVariant() has been called with the determined code.
 * @throws  None — all errors are handled internally and reflected in variantReadSuccess_.
 * @note    Called by: ProbeApp. Call condition: Startup.
 * @warning Must be called before any feature-check methods are invoked.
 * @see     SetVariant()
 * @requirements SWR-REQ-01-03-001;SWR-REQ-03-14-001
 * @rationale Returns std::string to decouple the caller from raw buffer management
 *            and to allow straightforward dictionary lookup in SetVariant().
 */
std::string ProbeCommVariant::ReadVariantCode()
{
    // Attempt to read variant code from shared memory interface.
    const SharedMemReadResult readResult{SharedMemory_VariantCode_Read()};

    if (readResult.success == true)
    {
        // Assign the retrieved variant code.
        variantCode_null    = readResult.value;
        variantReadSuccess_ = true;
    }
    else
    {
        // Shared memory read failed; apply fallback.
        variantCode_null    = defaultVariantCode_null;
        variantReadSuccess_ = false;
        // Log the read failure for diagnostics.
        std::cerr << "ReadVariantCode: shared memory read failed; applying default variant code\n";
    }

    // Invoke variant resolution with the determined code.
    SetVariant(variantCode_null);

    // Return the active variant code to the caller.
    return variantCode_null;
}

// ============================================================
// SetVariant (PV-004)
// ============================================================

/**
 * @brief   Applies feature flags by matching the supplied variant code against the variant dictionary.
 * @details Loads the variant dictionary from variantDictionaryPath_null via LoadDictionary().
 *          If the load fails, LOG_ERROR is emitted and HandleMissingVariantCode() is called.
 *          If the load succeeds, FindEntry() is called with code. If the entry is not found,
 *          LOG_ERROR is emitted and HandleMissingVariantCode() is called. If the entry is found,
 *          each feature flag is set to true when the corresponding dictionary value equals "A",
 *          and false otherwise. daqTransmissionEnabled_ is set to true unconditionally on a
 *          successful lookup. A LOG_INFO diagnostic is emitted recording the applied flags.
 *          Executes deterministically within bounded iteration over at most five feature keys.
 * @param[in] code  The variant code string to look up. Must be exactly kVariantCodeLength
 *                  characters. An empty or incorrectly sized string is treated as invalid.
 *                  Valid range: 5-character ASCII string or empty string (triggers fallback).
 * @pre     ReadVariantCode() must have been called. code must be a valid std::string.
 * @post    Feature flags reflect the variant dictionary entry for code, or all flags are
 *          false if code was not found or was invalid.
 * @throws  None — all error paths are handled internally.
 * @note    Called by: ProbeApp. Call condition: Startup.
 * @warning Calling this method more than once will overwrite previously set feature flags.
 * @see     ReadVariantCode(), HandleMissingVariantCode(), DisableAllTransmissionOnInvalidVariant()
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Separating read and set operations allows ProbeApp to inspect the raw code
 *            before committing to feature-flag application.
 */
void ProbeCommVariant::SetVariant(const std::string& code)
{
    // Load the variant dictionary from configured path.
    const DictionaryLoadResult dictionaryLoadResult{LoadDictionary(variantDictionaryPath_null)};

    if (dictionaryLoadResult.success == false)
    {
        // Dictionary file missing or parse error.
        std::cerr << "SetVariant: variant dictionary load failed at path: "
                  << variantDictionaryPath_null << "\n";
        HandleMissingVariantCode();
        return;
    }

    // Search for the variant code entry in the dictionary.
    const DictionaryEntry dictionaryEntry{dictionaryLoadResult.FindEntry(code)};

    if (dictionaryEntry.found == false)
    {
        // Variant code not present in dictionary.
        std::cerr << "SetVariant: variant code not found in dictionary: " << code << "\n";
        HandleMissingVariantCode();
        return;
    }

    // Apply feature flags based on dictionary entry values.
    // Activation value is "A"; all others mean disabled.
    if (dictionaryEntry.regularProbeValue == "A")
    {
        regularProbeEnabled_ = true;
    }
    else
    {
        regularProbeEnabled_ = false;
    }

    if (dictionaryEntry.eventProbeValue == "A")
    {
        eventProbeEnabled_ = true;
    }
    else
    {
        eventProbeEnabled_ = false;
    }

    if (dictionaryEntry.eventProbeWithoutPictureValue == "A")
    {
        eventProbeWithoutPictureEnabled_ = true;
    }
    else
    {
        eventProbeWithoutPictureEnabled_ = false;
    }

    if (dictionaryEntry.gedrValue == "A")
    {
        gedrEnabled_ = true;
    }
    else
    {
        gedrEnabled_ = false;
    }

    if (dictionaryEntry.gedrWithoutPictureValue == "A")
    {
        gedrWithoutPictureEnabled_ = true;
    }
    else
    {
        gedrWithoutPictureEnabled_ = false;
    }

    // Enable DAQ transmission since variant code was resolved.
    daqTransmissionEnabled_ = true;

    // Log all applied flag states for diagnostics.
    std::cout << "SetVariant: flags applied for code: " << code << "\n";
}

// ============================================================
// CheckRegularProbeEnabled (PV-005)
// ============================================================

/**
 * @brief   Returns whether regular probe data collection is enabled for the active variant.
 * @details Reads regularProbeEnabled_ and returns its current value without modifying any
 *          state. The caller uses the returned boolean to gate regular probe signal sampling
 *          and transmission. Execution is bounded and deterministic in O(1).
 * @return  bool indicating the enabled state of regular probe data collection.
 * @retval  true   Regular probe data collection is enabled for the active variant.
 * @retval  false  Regular probe data collection is disabled, or variant was not resolved.
 * @pre     SetVariant() should have been called at startup for a meaningful result.
 * @post    No state is modified.
 * @throws  None.
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 */
bool ProbeCommVariant::CheckRegularProbeEnabled() const noexcept
{
    // Return the current state of the regular probe feature flag.
    return regularProbeEnabled_;
}

// ============================================================
// CheckEventProbeEnabled (PV-006)
// ============================================================

/**
 * @brief   Returns whether event probe data collection is enabled for the active variant.
 * @details Reads eventProbeEnabled_ and returns its current value without modifying any
 *          state. Execution is bounded and deterministic in O(1). The caller uses the
 *          returned value to gate event probe processing.
 * @return  bool indicating the enabled state of event probe data collection.
 * @retval  true   Event probe data collection is enabled for the active variant.
 * @retval  false  Event probe data collection is disabled, or variant was not resolved.
 * @pre     SetVariant() should have been called at startup for a meaningful result.
 * @post    No state is modified.
 * @throws  None.
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 */
bool ProbeCommVariant::CheckEventProbeEnabled() const noexcept
{
    // Return the current state of the event probe feature flag.
    return eventProbeEnabled_;
}

// ============================================================
// CheckEventProbeWithoutPictureEnabled (PV-007)
// ============================================================

/**
 * @brief   Returns whether event probe without picture is enabled for the active variant.
 * @details Reads eventProbeWithoutPictureEnabled_ and returns its current value without
 *          modifying any state. Execution is deterministic and bounded in O(1).
 * @return  bool indicating the enabled state of event probe without picture.
 * @retval  true   Event probe without picture is enabled for the active variant.
 * @retval  false  Event probe without picture is disabled, or variant was not resolved.
 * @pre     SetVariant() should have been called at startup for a meaningful result.
 * @post    No state is modified.
 * @throws  None.
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 */
bool ProbeCommVariant::CheckEventProbeWithoutPictureEnabled() const noexcept
{
    // Return the current state of the event probe without picture feature flag.
    return eventProbeWithoutPictureEnabled_;
}

// ============================================================
// CheckGedrEnabled (PV-008)
// ============================================================

/**
 * @brief   Returns whether GEDR data collection is enabled for the active variant.
 * @details Reads gedrEnabled_ and returns its current value without modifying any state.
 *          Execution is deterministic and bounded in O(1).
 * @return  bool indicating the enabled state of GEDR data collection.
 * @retval  true   GEDR data collection is enabled for the active variant.
 * @retval  false  GEDR data collection is disabled, or variant was not resolved.
 * @pre     SetVariant() should have been called at startup for a meaningful result.
 * @post    No state is modified.
 * @throws  None.
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 */
bool ProbeCommVariant::CheckGedrEnabled() const noexcept
{
    // Return the current state of the GEDR feature flag.
    return gedrEnabled_;
}

} // namespace probe

/// @namespace probe
/// @brief Contains all components of the probe application.
namespace probe {

/**
 * @brief   Returns whether GEDR without picture is enabled for the active variant.
 * @details Provides a const, noexcept accessor for the gedrWithoutPictureEnabled_ flag that
 *          was set by SetVariant(). Returns false if SetVariant() has not yet been called or
 *          if the variant code was not found in the dictionary. Execution is deterministic
 *          and bounded in O(1). No state is modified by this call.
 * @return  bool indicating the enabled state of GEDR without picture.
 * @retval  true   GEDR without picture is enabled for the active variant.
 * @retval  false  GEDR without picture is disabled, or variant was not resolved.
 * @pre     SetVariant() should have been called at startup for a meaningful result.
 * @post    No state is modified.
 * @throws  None — function is noexcept.
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @see     SetVariant(), DisableAllTransmissionOnInvalidVariant()
 * @requirements SWR-REQ-01-03-002;SWR-REQ-03-14-002
 * @rationale Direct member read ensures O(1) deterministic execution with no side effects,
 *            satisfying ASIL-B determinism requirements.
 */
[[nodiscard]] bool ProbeCommVariant::CheckGedrWithoutPictureEnabled() const noexcept
{
    return gedrWithoutPictureEnabled_;
}

/**
 * @brief   Returns whether DAQ transmission is enabled for the active variant.
 * @details Provides a const, noexcept accessor for the daqTransmissionEnabled_ flag that was
 *          set by SetVariant(). Per SWR-REQ-01-03-003, this flag is explicitly set to false
 *          when the variant code is not found in the dictionary, preventing any unintended
 *          data transmission to the DAQ system. Execution is deterministic and bounded in O(1).
 *          When this flag is false, the calling context must suppress all outbound messages
 *          to DAQ to prevent transmission to an unconfigured destination.
 * @return  bool indicating the enabled state of DAQ transmission.
 * @retval  true   DAQ transmission is enabled for the active variant.
 * @retval  false  DAQ transmission is disabled; variant code was not found or is invalid.
 * @pre     SetVariant() should have been called at startup for a meaningful result.
 * @post    No state is modified.
 * @throws  None — function is noexcept.
 * @note    Called by: ProbeApp. Call condition: On_Request.
 * @see     SetVariant(), DisableAllTransmissionOnInvalidVariant()
 * @requirements SWR-REQ-01-03-002;SWR-REQ-01-03-003;SWR-REQ-03-14-002
 * @rationale Direct member read ensures O(1) deterministic execution with no side effects,
 *            satisfying ASIL-B determinism requirements. Explicit false-on-invalid-variant
 *            enforces fail-safe DAQ suppression per SWR-REQ-01-03-003.
 */
[[nodiscard]] bool ProbeCommVariant::CheckDaqTransmissionEnabled() const noexcept
{
    return daqTransmissionEnabled_;
}

/**
 * @brief   Logs an error condition and prevents data transmission when the variant code is absent.
 * @details Called internally by SetVariant() when the supplied variant code is not found in
 *          the variant dictionary. Emits a diagnostic message to std::cerr identifying the
 *          unrecognised code and the variantReadSuccess_ state to provide full diagnostic context,
 *          then delegates to DisableAllTransmissionOnInvalidVariant() to enforce the fail-safe
 *          state. This two-step design separates diagnostic reporting from state mutation,
 *          satisfying the single-responsibility principle (M7). After this call, no data
 *          collection or transmission to DAQ or GEDR is possible until a system restart
 *          provides a valid variant. Execution is deterministic and bounded.
 * @pre     variantCode_ must contain the code that failed lookup.
 * @post    DisableAllTransmissionOnInvalidVariant() has been called; all feature flags are false.
 * @throws  None — all error paths are handled internally.
 * @note    Called by: ProbeCommVariant (internal). Call condition: Startup.
 * @warning Must only be called from SetVariant(). Do not call directly from external code.
 * @see     DisableAllTransmissionOnInvalidVariant(), SetVariant()
 * @requirements SWR-REQ-01-03-003;SWR-REQ-03-14-003
 * @rationale Isolating the error-logging step allows unit tests to verify diagnostic output
 *            independently of the flag-reset logic. Using std::cerr ensures no dynamic
 *            allocation and complies with the no-printf coding standard rule.
 */
void ProbeCommVariant::HandleMissingVariantCode()
{
    std::cerr << "HandleMissingVariantCode: variant code not resolved: "
              << variantCode_null
              << " readSuccess: "
              << variantReadSuccess_
              << "\n";

    DisableAllTransmissionOnInvalidVariant();
}

/**
 * @brief   Disables all data-sending feature flags when the variant is invalid or unrecognised.
 * @details Sets regularProbeEnabled_, eventProbeEnabled_, eventProbeWithoutPictureEnabled_,
 *          gedrEnabled_, gedrWithoutPictureEnabled_, and daqTransmissionEnabled_ all to false
 *          in a sequential, unconditional manner. There are no conditions or branches. No
 *          external service is accessed. After this function returns, all check functions
 *          (CheckRegularProbeEnabled, CheckEventProbeEnabled, CheckEventProbeWithoutPictureEnabled,
 *          CheckGedrEnabled, CheckGedrWithoutPictureEnabled, CheckDaqTransmissionEnabled) will
 *          return false, preventing any data flow. A LOG_INFO diagnostic message is then emitted
 *          to std::cout to record the disablement for diagnostic traceability. Execution is
 *          deterministic and bounded in O(1).
 * @pre     None — safe to call in any state.
 * @post    All six feature-flag members are false.
 * @throws  None — function is noexcept.
 * @note    Called by: ProbeCommVariant (internal). Call condition: Startup.
 * @warning This method unconditionally clears all flags. Any previously set flags will be lost.
 * @see     HandleMissingVariantCode()
 * @requirements SWR-REQ-01-03-003;SWR-REQ-03-14-003
 * @rationale Centralising the flag-reset logic in a dedicated method ensures that no flag
 *            is accidentally omitted when the invalid-variant path is taken, satisfying
 *            the fail-safe requirement of SWR-REQ-01-03-003 and SWR-REQ-03-14-003.
 */
void ProbeCommVariant::DisableAllTransmissionOnInvalidVariant() noexcept
{
    regularProbeEnabled_                = false;
    eventProbeEnabled_                  = false;
    eventProbeWithoutPictureEnabled_    = false;
    gedrEnabled_                        = false;
    gedrWithoutPictureEnabled_          = false;
    daqTransmissionEnabled_             = false;

    std::cout << "DisableAllTransmissionOnInvalidVariant: all transmission flags disabled\n";
}

} // namespace probe